### ISSUE TITLE
Harmless reminder

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/Series4#1]
Some of sets of compounds that are missing from the wiki:
Edwin Tse's ether-triazole series (all were inactive)
The sulfur bearing series (all were inactive or otherwise undesirable) 
MMV897711/12 (LHS aryl methoxy mod)

**Comment by edwintse** [comment]
A section has been added to the wiki for data such as this. Linked [here](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections).
