### ISSUE TITLE
Series 4 vs. Drug Resistant Strains

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series4#11]
A while back now Series 4 was examined for activity against drug-resistant strains of malaria. OSM obtained the data on March 21st 2017 but (apologies - my bad) this sat in an email until now (this is the problem with email). I've finally gotten round to posting the data, [here](https://au-mynotebook.labarchives.com/share/Matthew%2520Houghton%2520Todd/MzkuMHwxNTQvMzAvVHJlZU5vZGUvMTkwOTE5NjM5NXw5OS4w).

The compound was evaluated at Swiss TPH. In summary the data are good for the series. No cross-resistance was observed. The compound used was MMV669844 (OSM-S-218) - sample held by SPECS/MMV. This is a chiral compound, though we're not sure of the ee. The compound, when synthesized since then as a racemate, has the code MMV897709.

<img src="https://user-images.githubusercontent.com/4386101/33546665-bd3c6238-d935-11e7-85d5-5216cc00f19d.png" alt="Activity of Representative Series 4 Compound vs. Drug Resistance Strains" height="300">

![Potency vs Drug Resistant Strains of Malaria](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/blob/master/Schemes/OSM-S-218%20drug%20resistance.png)

Comments welcome, otherwise this issue can be closed since a note about the results has been posted in the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Potency-vs.-Resistant-Strains) and I've inserted a note into the [Series 4 paper](http://tinyurl.com/OSM-S4-Paper1) to ensure that this important property of the series is mentioned.

**Comment by mattodd** [comment]
For completeness would anyone like to annotate the list of strains with the relevant drugs to which they are resistant?
Dd2, Dd2 DDD107498, Dd2 FOS-R, Dd2 390048, Dd2 DSM265, Dd2 GNF156, Dd2 ELQ300, NF54, K1, 7G8, TM90C2B, Cam3.I (MRA1240)

**Comment by david1597** [comment]
## To be completed...


  | Atovaquone | Chloroquine | Cycloguanil | Pyrimethamine
-- | -- | -- | -- | --
NF54 | No | No | No | No
TM90C2B | Yes | No | No | No
K1 | No | Yes | Yes | Yes
7G8 | No | Yes | Yes | Yes
DD2 | No | Yes | Yes | Yes




Source: http://aac.asm.org/content/59/2/1110

**Comment by danaklug** [comment]
Here are the Dd2-derived strains. If I'm not mistaken these strains are resistant to chloroqine, cycloguanil, and pyrimethamine in addition to the compounds listed below.

Dd2 DDD107498: Resistant to DDD107498 (Baragana 2015, DOI: 10.1038/nature14451).
Dd2 FOS-R: Resistant to fosmidomycin (Dharia 2009, DOI: 10.1186/gb-2009-10-2-r21).
Dd2 390048: Resistant to MMV390048 (Paquet 2017, DOI: 10.1126/scitranslmed.aad9735).
Dd2 DSM265: Resistant to DSM265 (Phillips 2015, DOI: 10.1126/scitranslmed.aaa6645).
Dd2 GNF156: Resistant to GNF156 (Lim 2016, DOI: 10.1038/nmicrobiol.2016.166; LaMonte 2016, DOI: 10.1128/mBio.00696-16).
Dd2 ELQ300: Resistant to ELQ-300 (Nilsen 2013, DOI: 10.1126/scitranslmed.3005029). _Note_: The reference here actually states that no resistance to ELQ-300 was observed... I assume at some point this strain was developed but couldn't find a reference for it. Information on the compound itself presented in the reference.

**Comment by mattodd** [comment]
Linked to wiki, and data included in paper. Closing.
