### ISSUE TITLE
Update on Scott Obach's Biofunctionalization Experiments

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series4#13]
In light of the spectacular potency obtained from one of the compounds Scott Obach produced through biofunctionalisation of existing OSM compounds (OpenSourceMalaria/OSM_To_Do_List#529), we sent four other compounds to him in September.  

This is a work in progress, but here is where we are, with explanatory text below:

![initial likely pfizer products copy](https://user-images.githubusercontent.com/4386101/33537049-8cb84d0c-d90d-11e7-8432-6883994c59ab.png)

ELN entry [here](https://au-mynotebook.labarchives.com/share/Matthew%2520Houghton%2520Todd/NDEuNnwxNTQvMzIvVHJlZU5vZGUvNjI0MjE1MzUxfDEwNS42).

On Oct 11th, Scott wrote (I'm paraphrasing):

1. The two compounds with the benzylic OH (MMV672687 and MMV688896) did nothing interesting—just got oxidized up to the ketone.  I’m assuming that this is not of interest, or is it?

**Response**: Correct: [Ketones are not too interesting](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/NzEyLjR8MTUwOS81NDgvVHJlZU5vZGUvMzU4OTEzMDg4N3wxODA4LjM5OTk5OTk5OTk5OTk).

2.  MMV897700 in the screen appeared to yield oxidations on the cubane.  I haven’t scaled this one up yet.

**Response**: Oxidation of the cubane is definitely interesting (we were kind of hoping this would happen). There would of course be an excellent comparison to be made with the phenyl oxidation product.

3.  Based on the screen data, I scaled up MMV1557938 biosynthesis first and got a great yield of two products. HRMS and NMR (1D and 2D) showed that these were the two stereoisomeric epoxides coming from the alkene of the norbornene moiety.  Now the complexity – they seem to both be slowly hydrolyzing to the dihydrodiols.  I will keep tabs on this conversion.  I’m suspecting that the diols would be of greater interest than unstable epoxides, correct?  

**Response**: Oxidation of the norbornene is interesting. You're correct in saying that we'd most likely be interested in the more "stable" diol than the epoxide, yes. If we could obtain samples of these latter two compounds for potency evaluation at Dundee, that'd be very good indeed.

On 24th Oct, Scott updated us by email:

The two products from the norbornene seemed to have stayed where they are—that is, they each have a mixture of epoxide and dihydrodiol.  I added D2O to them and left them on the bench overnight  but they didn’t budge; and then I added a little deuterated formic acid and surprisingly they still didn’t convert any further to the dihydrodiols.  Since the UV chromophore doesn’t change, I can make a good estimate of the % that is epoxide and % that is dihydrodiol from my HPLC runs.  These can then be tested as mixtures and if anything interesting comes out of that worthy of further pursuit we can figure out how to get the dihydrodiol pure.  What’s odd is that each epoxide only gives one dihydrodiol peak—I would have thought that I’d get a mixture of diastereomers—or maybe I do and they’re perfectly coeluting.

I’ll go to the cubane next and if/when I get products from that, we’ll send everything to Scotland all at one time.

...which is where we currently sit. Interesting results in progress. Will add to this GHI when we hear more.

**Comment by MFernflower** [comment]
The chiral alcohol becoming a ketone while not chemically interesting poses a possible methodology for in vivo testing - the alcohol behaves as a prodrug for the ketone and since both are active we increase amount of time of activity we have  in the body @mattodd

**Comment by mattodd** [comment]
Further to the above, an update on 19/12/17 from Scott by email:

"An early Christmas gift—I have four products ready for testing from MMV-897700 and MMV-1557938 substrates.

Important though, is that the two epoxides from 1557938 have partially converted to the respective dihydrodiols (of unknown absolute configuration).  So when testing those, we have to assume it’s some sort of unknown mixture of two or three analogues (epoxide plus _cis_ diol and/or _trans_ diol), but we know the total concentration of all three. If one of these mixtures comes back as a hit of interest, then we’ll have to devise a plan to figure out what is important.  NMR did give the exact configuration of the epoxide—but was the stereocenter on the connecting carbon known in the starting material?

The cubane OH products are more straightforward.  

Here are the concentrations—there is about 30 uL or so of each, in d6-DMSO

PF-7091172 = 9.8 mM (mix)
PF-7091173 = 10.8 mM (mix)
PF-7091175 = 1.0 mM
PF-7091176 = 3.3 mM

Please re-send me the shipping address for your collaborator in Scotland as I do not have that anymore.  To avoid any hold-up in shipping due to the holidays, I’ll send them out first thing in January.  And if you want to assign them MMV registry numbers, please do and send these to me so I’ll label the vials with them."

Answers:
a) This is _very_ cool.
b) Pretty sure we don't know the absolute config of S/M, @edwintse ?
c) Address for Dundee group being sent to you offline.
d) @david1597 will be in touch with the MMV numbers - we have reached out to the MMV informatics people to check what they usually do for mixtures where the exact composition is not known. We suspect they just get assigned numbers that may ultimately become redundant.


![confirmed pfizer products](https://user-images.githubusercontent.com/4386101/34240232-99af1ed6-e660-11e7-802b-03a77fbb5d3c.png)


[Confirmed Pfizer Products.zip](https://github.com/OpenSourceMalaria/Series4/files/1577884/Confirmed.Pfizer.Products.zip)

**Comment by david1597** [comment]
Thanks to @edwintse for registering these compounds over the break. 

PF-7091172 => MMV1577922
PF-7091173 => MMV1577923
PF-7091175 => MMV1577924
PF-7091176 => MMV1577925

Compounds were shipped directly to Dundee from Scott Obach. Results should come through towards the end of the month when Dundee are back up and running for 2018.

**Comment by MFernflower** [comment]
Has IC50 data on these metabolites been posted yet? @mattodd

**Comment by david1597** [comment]
@MFernflower Thanks for the reminder - we have the data but hadn't got around to posting it.

Unfortunately, all four compounds were inactive.

MMV1577922  > 9.8 µM
MMV1577923  > 11 µM
MMV1577924  > 1 µM
MMV1577925  > 3.3 µM

The reason they show different '>' values is due to how these particular samples are received. Normally, we ship Sydney samples as solids and then it's largely automated on the Dundee side with concentrations made up to 10 µM and diluted. These samples from Scott are sent already in solution, and in smaller amounts due to the nature of the work, and so the concentrations above represent the concentration sent to Dundee and hence the max concentration that could be tested. From Dundee - "None of the compounds showed activity above 50% inhibition in the assay therefore ‘>’ indicates that the potency (IC50) is greater than the maximum concentration tested."

**Comment by MFernflower** [comment]
Data from this test needs to be added to wiki and issue closed when possible

**Comment by david1597** [comment]
Potency data has been added to the [master list](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618) and to the ['Biological Data currently not incorporated into the main Wiki sections'](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections) section of the wiki. The values are the result of one run.

![pfizer ii](https://user-images.githubusercontent.com/30584472/37750876-3c932196-2de3-11e8-936a-aa4bc2acdaa4.jpg)
[Pfizer II.zip](https://github.com/OpenSourceMalaria/Series4/files/1836049/Pfizer.II.zip)
