### ISSUE TITLE
Further potential compounds to make with 2-phenylpropan-1-ol fragments

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#17]
There are, to date, three compounds containing the 2-phenylpropan-1-ol fragment:

![a](https://user-images.githubusercontent.com/30584472/34025185-9a4263c0-e1a2-11e7-91ff-03d40884127f.jpg)

We've discussed the first and third in that row a lot...current synthetic efforts are already heavily focused on exploring H-bond donor analogues of OSM-S-412 (#3), itself initially arising from a biosynthesis using MMV693155 (OpenSourceMalaria/OSM_To_Do_List/issues/513) and we have a poll to investigate this further: OpenSourceMalaria/OSM_To_Do_List/issues/555.

Looking back through the inherited compounds I realised that MMV670947 also has a similar structure, and has good potency. So, should we not just be focused on H-bond donors on that ring but investigating substitution more widely? We had begun to discuss that already a little across at #3.

All of the following, some probably better ideas than others, could be made in our labs with chemicals we already have available to us through the following methodology. 

![c](https://user-images.githubusercontent.com/30584472/34025596-c72d410a-e1a4-11e7-897f-93012b7dbb98.jpg)
_____________________________________________________________________________________________________
![b](https://user-images.githubusercontent.com/30584472/34025552-8cc1371a-e1a4-11e7-9e0e-b71dd4912097.jpg)

**Comment by MFernflower** [comment]
Do you guys have cyclohexyl iodine on hand?

**Comment by MFernflower** [comment]
@david1597 This was something I came up with and I'm pretty proud of it: https://mynotebook.labarchives.com/share/O_S_M%2520Proposed%2520Molecules/MjguNnwyNjI3NDkvMjIvVHJlZU5vZGUvNDA0MTg4ODI2OXw3Mi42

**Comment by MFernflower** [comment]
@david1597 Random Q - How will the cyanide group survive reduction?

**Comment by mattodd** [comment]
@MFernflower it'll depend how hard you hit it, and what with. A search on e.g. SciFinder for pertinent examples will be the step you take before you enter the lab.

**Comment by MFernflower** [comment]
Re-posted from slack:
This will squash any fears of quinone formation and can easy be oxidized to an acetyl compound
![alcoholfragmentdavid](https://user-images.githubusercontent.com/3164942/34470172-8ec47ab0-eef9-11e7-8942-0a454881da06.png)

**Comment by MFernflower** [comment]
A compound made from this precursor might be an interesting idea (phenolic OH to ring nitrogen same position) 

![mfcd02093937-large](https://user-images.githubusercontent.com/3164942/35191106-4948a960-fe40-11e7-94ee-99208f09d744.png)

**Comment by david1597** [comment]
Some of the suggestions above were incorporated into the poll in OpenSourceMalaria/OSM_To_Do_List#555 which was used to plan which compounds to make in this series. 

Those that were successfully made will be listed in #3.
