### ISSUE TITLE
Appeal for making modified "acid test" compound

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/Series4#19]
Provided the team at USyd ( @david1597 and @JoshMaxwell ) gets a large enough yield of compound 'P' (or 'S') (see issue #555) I would like to see some stock of the compound oxidized to it's alkyl carboxylic acid sodium salt via a two step method that I discussed with @mcoster in slack. That method being oxidation of 'P' (or 'S')  to an aldehyde with DMP in toluene followed by a textbook Pinnick oxidation of the resultant aldehyde and subsequent extraction and sodium salt formation of the final carboxylic acid product.

I believe this is an important thing to test as it seems pretty likely the alkyl alcohol fragment of the Pfizer phenol will be converted to a carboxylic acid by various liver enzymes (We should ask Scott for confirmation @mattodd) 

![firstpass](https://user-images.githubusercontent.com/3164942/35190412-f2867bc2-fe2e-11e7-8b06-241b32675a8f.png)

**Comment by MFernflower** [comment]
Closing because @edwintse has cracked the case!

**Comment by mattodd** [comment]
Hey @MFernflower thanks for closing - great. If at all possible please link to things that have influenced the closing of an issue, to allow back-tracking. Here it's https://github.com/OpenSourceMalaria/Series4/issues/22 or, using a formalism that (should) install a back link it's (fingers crossed) OpenSourceMalaria/Series4#22

**Comment by MFernflower** [comment]
Issue will be reopened when potency of parent carboxylic acid compound is confirmed
