### ISSUE TITLE
The hERG Evador has been successfully synthesised

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/Series4#22]
The hERG evador has been a key target compound for this series first brought up in [#390](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/390) concerning potency. The synthesis of this compound was first picked up by Haverford College ([#405](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/405)) with the corresponding primary alcohol successfully synthesised. Attempts at oxidising this to the acid were not attempted/unsuccessful due to time constraints ([#427](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/427), [#451](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/451)).

I ended up using a much shorter 2 step synthesis shown below (not counting the synthesis of the core compound) involving direct SN2 displacement using 2-phenylpropane-1,3-diol and subsequent oxidation using Jones reagent (CrO3/H2SO4).

![untitled wiley-9](https://user-images.githubusercontent.com/18062981/36187375-faaeffd6-1198-11e8-9857-dd226d973165.jpeg)

ELN entries for [SN2 displacement](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/Nzk2Ljl8MTUwOS82MTMvVHJlZU5vZGUvMzE0NDI0MTIxNnwyMDIyLjg5OTk5OTk5OTk5OTk=) and [oxidation](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/Nzk5LjV8MTUwOS82MTUvVHJlZU5vZGUvNDE5MjI4NjIyN3wyMDI5LjU=).
The identity of the compound has been confirmed by [1H](https://github.com/OpenSourceMalaria/Series4/files/1722608/1H.pdf), [13C](https://github.com/OpenSourceMalaria/Series4/files/1722609/13C.pdf), [IR](https://github.com/OpenSourceMalaria/Series4/files/1722610/IR.pdf) and [LRMS](https://github.com/OpenSourceMalaria/Series4/files/1722612/LRMS.pdf) (pdfs attached).
Characterisation of the corresponding primary alcohol attached for comparison ([1H](https://github.com/OpenSourceMalaria/Series4/files/1722635/1H.pdf), [13C](https://github.com/OpenSourceMalaria/Series4/files/1722636/13C.pdf), [IR](https://github.com/OpenSourceMalaria/Series4/files/1722637/IR.pdf) and [LRMS](https://github.com/OpenSourceMalaria/Series4/files/1722638/LRMS.pdf)).

This compound will be sent off for biological evaluation in the next batch, with hERG studies commencing shortly after.

----------------------------------------------------------------------------------------------------
**Removed from the DCNYS section of the wiki**

The **hERG Evador/Acid Test** (carboxylic acid analogue of MMV688896): [Comment on desirability](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/390), [Synthesis proposal](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/405), [First synthesis attempt, summary and suggestions of ways forward](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/427) with [ELN](http://malaria.ourexperiment.org/chem_301_fall_2016_a), [Discussion of synthetic roadblock](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/451), [Discussion of Rationale](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/452), [Griffith Uni proposed synthesis](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/521). [Some comments on progress from Haverford College student](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/508).

----------------------------------------------------------------------------------------------------
**Strings**

FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C(O)=O)C4=CC=CC=C4)N32
InChI=1S/C21H16F2N4O4/c22-21(23)31-15-8-6-14(7-9-15)19-26-25-17-10-24-11-18(27(17)19)30-12-16(20(28)29)13-4-2-1-3-5-13/h1-11,16,21H,12H2,(H,28,29)
FICNFVPYGUTYFV-UHFFFAOYSA-N

**Comment by edwintse** [comment]
@mattodd This compound can now be removed from the DCNYS of the wiki.

**Comment by mcoster** [comment]
Woohoo, well done, Ed!

**Comment by edwintse** [comment]
Compound has been removed from the DCNYS section (text copied over above).
Closing.
