### ISSUE TITLE
The 'Pfizer phenol'/OSM-S-412 has been successfully synthesised

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#23]
Finally!
 
![osm-s-412](https://user-images.githubusercontent.com/30584472/36623135-336d7f36-1956-11e8-96a9-6cc80718dd31.jpg)

### Brief background 
The 'Pfizer phenol' originated from a biosynthesis of a compound that itself was originally synthesised in the lab here in Sydney - details at OpenSourceMalaria/OSM_To_Do_List#513. This biosynthesis product showed excellent potency, and with optimism of improved solubility, we set out to synthesis this in the lab. It has taken some time with quite a few synthetic obstacles on the way but we now have the product.

### Characterisation

1H-NMR  

![1h](https://user-images.githubusercontent.com/30584472/36623093-dea91118-1955-11e8-8245-22ae6668d929.png)
Two pairs of doublets for the LHS and RHS aromatics. Two singlets at 9.03 and 7.59 ppm for the core protons. A triplet for the OCHF2 at 7.35. Phenolic OH at 9.18, the other OH at 4.72, one of the CH2's between 4.4 and 4.5 and the CH at 2.88. 'Missing' is the other CH2 - it is obscured by the HOD peak at 3.3. 

Delving into the COSY 
![cosy](https://user-images.githubusercontent.com/30584472/36623063-b63e4dba-1955-11e8-8d21-fe6620940f2f.png)
 we can see that both the CH at 2.88 ppm and OH at 4.72 ppm couple with a peak at ~3.3 ppm.

The HSQC 
![hsqc](https://user-images.githubusercontent.com/30584472/36623072-bbcec0f2-1955-11e8-98ab-0bb8cc6bf27e.png)

The HMBC 
![hmbc](https://user-images.githubusercontent.com/30584472/36623076-c0dfb8bc-1955-11e8-8361-e29a213a1386.png)
 shows correlation between this 3.3 ppm proton resonance and the other CH2 carbon (71.9 ppm), the CH carbon (45.7 ppm) and one of the aromatics (129.6 ppm).

13C NMR has the expected number of peaks.

![13c](https://user-images.githubusercontent.com/30584472/36623159-6e0624ae-1956-11e8-8b91-515a61b7aec2.png)

19F NMR also shown

![19f](https://user-images.githubusercontent.com/30584472/36623310-90e1fa9c-1957-11e8-9257-2763e8be97f0.jpeg)

Mass spec (low-res) shows a peak at +451 corresponding to mass plus sodium. 
![image](https://user-images.githubusercontent.com/30584472/36623272-3be9026a-1957-11e8-9846-a603bf6fdd92.png)

### The synthesis 

![rxn](https://user-images.githubusercontent.com/30584472/36623349-e5f509fc-1957-11e8-8506-1564dc6df7ef.jpg)
[OSM-S-412 scheme.zip](https://github.com/OpenSourceMalaria/Series4/files/1755778/OSM-S-412.scheme.zip)

Looks remarkably simple, doesn't it? The final route is slightly different to that discussed before as the phenolic OH remained unprotected throughout. Arylation of diethyl malonate followed by reduction gave the triol. This triol was then coupled with the ready synthesised core to give the final molecule. Coupling conditions were using NaH. Our previously used go-to methods of either KOtBu or KOH/crown ether did not work in this case (both of which were tried initially). The final product was purified using reverse-phase column chromatography. Again, initial purification attempts were unsuccessful as the product appeared to decompose on silica.

[ELN link](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjExLjl8MzAxNzEvMTYzL1RyZWVOb2RlLzE2Nzc4NDg0MDZ8NTM3Ljk=) for final step
[ELN link](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjEzLjIwMDAwMDAwMDAwMDAyfDMwMTcxLzE2NC9UcmVlTm9kZS84MDUwOTgyMTd8NTQxLjE5OTk5OTk5OTk5OTk=) for reduction
[ELN link](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjA0LjF8MzAxNzEvMTU3L1RyZWVOb2RlLzk1NzAxMjAwOHw1MTguMQ==) for phenol arylation

### Biological testing
The compound is being shipped to Dundee for potency testing on Monday.

### The discrepancy between the characterisation data for this product and the original Pfizer biosynthesis
Saved till the end - and I'm putting this in a separate issue - #24 as (I think) this should make things easier to follow. The 1H NMR data do not match - this may be the cause of the differences in potency discussed in #20.

Strings for OSM-S-412 / MMV1557865:
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)C4=CC=C(O)C=C4)N32
InChI=1S/C21H18F2N4O4/c22-21(23)31-17-7-3-14(4-8-17)20-26-25-18-9-24-10-19(27(18)20)30-12-15(11-28)13-1-5-16(29)6-2-13/h1-10,15,21,28-29H,11-12H2
OBCDILCAJSSYWKE-UHFFFAOYSA-N

_Edited for: updated links to ELN, other Issues, chemdraw file, and inclusion of strings_

**Comment by mattodd** [comment]
Really great work, @david1597 !

Could you also please:

i) supply the ELN page where the raw data for the final compound are kept? (you can just edit your post above)
ii) In your post, give links to ELN pages for representative, individual steps, so that we can find the internal codes for the various intermediates when we need to hunt out data for the paper?
iii) Drag the Chemdraw for your synthesis scheme onto your post (you'll need to zip it) so we can re-use it for a description on the wiki etc?
iv) Paste SMILES, InChI and INCHIKEY for the Pfizer phenol onto the bottom of your post, given how important this page is for this compound. The structure also has identifiers MMV1557865 and OSM-S-412, which I'm pasting here just to aid searching. These codes are fine here, but *if* it turns out that the original compound was different, we'll need to go back and edit with a new code.

**Comment by david1597** [comment]
Closing this issue as the compound has been synthesised:
- compound with this structure has been made (this post and associated ELN links)
- biological testing results received (#26)

However, requires follow-up in other issues as:
- potency does not match that of the original Pfizer phenol (#20)
- NMR spectra of these two syntheses do not match (#24)
