### ISSUE TITLE
Discrepency between the characterisation data of the lab synthesis of OSM-S-412 vs. the biosynthesis

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#24]
As just mentioned in #23, the 'Pfizer phenol' has been synthesised in our labs. However, a comparison of the 1H NMR from our synthesis with the original biosynthesis highlights some issues. 

![image](https://user-images.githubusercontent.com/30584472/36623480-3a2ea78e-1959-11e8-9e90-ecb91c222be8.png)

1. There are very different chemical shifts of the aromatic doublets. 
2. There appears to be no phenolic OH in the biosynthesis NMR.
3. The CH peak may also be missing in the biosynthesis.

Concerns regarding quinone formation have been raised, we perhaps could have something like this in the biosynthesis (well, not this exact compound but along these lines):
![x](https://user-images.githubusercontent.com/30584472/36623561-efe9f75e-1959-11e8-925e-e2b90bbffed1.jpg)

It's been a little quiet from me as I finished that synthesis. I'm actively looking into this new issue, but wanted to start the discussion with the community as soon as possible - it looks like this story may not yet be complete!

**Comment by MFernflower** [comment]
Would a quinone like the one you showed react non-eznymatically with glutathione? If so we could mix the two chemicals together (no idea what solvent to use) and leave them overnight and then take an NMR of the resulting product (if any) 

@david1597 @drc007

**Comment by david1597** [comment]
@MFernflower 

Well we would first need to work out what the structure of the biosynthesised compound is (if indeed it isn’t what was initially proposed).

Then we’d actually need to synthesise that compound in the lab.

I can’t comment about the reactivity of quinones - I haven’t looked into it yet. What are you hoping to answer with your question?

**Comment by MFernflower** [comment]
Wondering if my idea could work as a simple quick test to see if the
biosynth product was a quinone -  Anyone have original stock of the
biosynth mystery compound?

**Comment by david1597** [comment]
There is about 30 uL of unknown conc. (~0.5 mM) in Dundee. But that’s been sat around at room temp for half a year so may be of limited use.

**Comment by david1597** [comment]
Closing issue. We now have the actual raw 1H data from the biosynthesis. It is compared to the lab chemical synthesis in detail in #33 which supersedes this issue.
