### ISSUE TITLE
LHS phenoxyethoxy compound

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/Series4#27]
This idea was the result of a chat on slack: 
![slack_convo](https://user-images.githubusercontent.com/3164942/37070621-52f2da30-2186-11e8-814e-cf645b4554ff.png)

SwissAdme predicts a 0.28 lower LogP between the proposed compound and mmv897698 - my only concern is the possible metabolic liability of the phenoxyethanol functional group!

![3 u2010 4 u2010 difluoromethoxy phenyl u20105 u2010 2 u2010phenoxyethoxy u2010 1 2 4 triazolo 4 3 u2010a pyrazine](https://user-images.githubusercontent.com/3164942/37070714-e0df60c0-2186-11e8-99dc-8ce61894d74e.png)

Thoughts everyone? 

Strings generated by: https://opsin.ch.cam.ac.uk/

InChI=1S/C20H16F2N4O3/c21-20(22)29-16-8-6-14(7-9-16)19-25-24-17-12-23-13-18(26(17)19)28-11-10-27-15-4-2-1-3-5-15/h1-9,12-13,20H,10-11H2

LIQWNTBRXAAMDF-UHFFFAOYSA-N 

FC(OC1=CC=C(C=C1)C1=NN=C2N1C(=CN=C2)OCCOC2=CC=CC=C2)F

**Comment by mcoster** [comment]
In going to the phenoxyethanol derived side chain, the chain lengthens by one compared to the highly active phenylethanol derived compounds. The molecule below would be the best comparator, but I couldn't find it by InChIKey - does anyone know if it has been made and tested?

![image](https://user-images.githubusercontent.com/28282596/37075083-c52d8808-221b-11e8-8103-7a8eabf37f5c.png)

InChI=1S/C21H18F2N4O2/c22-21(23)29-17-10-8-16(9-11-17)20-26-25-18-13-24-14-19(27(18)20)28-12-4-7-15-5-2-1-3-6-15/h1-3,5-6,8-11,13-14,21H,4,7,12H2

JNQZAPNWBVAOJV-UHFFFAOYSA-N

FC(F)OC1=CC=C(C=C1)C1=NN=C2C=NC=C(OCCCC3=CC=CC=C3)N12

**Comment by mattodd** [comment]
I'd thought we'd looked at it since in the document that summarised what was known of the series at the start of the project there was the sentence "Changing the length of the side-chain to anything other than 3 atoms severely lowers potency against PfNF54", but I don't see that compound in the relevant sheet.
https://github.com/OpenSourceMalaria/Series4/wiki/Pyrazine-Side-Chain-Modifications---Ethers

Either I'm missing it, or it wasn't made or it was made and tested but not included in the inherited dataset. Obviously we'd need to check that we're not missing an analogous compound with trivially different substitution on the two phenyls.

**Comment by MFernflower** [comment]
I suspect that info was found out by Pfizer but the relevant data was not
deposited in public data banks @mattodd so a rescreen might be needed as
data seems to have been lost

**Comment by MFernflower** [comment]
Are these two compounds slated for re eval at some point? @mattodd They can be made quickly with rather cheap precursor alcohols so I feel a re eval is a worthy task

**Comment by edwintse** [comment]
This had slipped under my radar but was mentioned again by @maratsydney last week. The compound with 3 CH2s is indeed absent from our Master List. The closest thing to the 3C chain are the phenylalaninol compounds (#30) that I recently made. I [made this compound](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/OTcyLjR8MTUwOS83NDgvVHJlZU5vZGUvMjc2NzI3MDMwNHwyNDY4LjQ=) last week and it'll be sent for eval in the batch this week.

Lucky for you @MFernflower, a group here has the phenoxyethanol reagent available. I've just [done the reaction](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/OTc1LjB8MTUwOS83NTAvVHJlZU5vZGUvMjM0NjAyMTQ0MXwyNDc1LjA=) this morning and it has now been columned and is drying. This will also be included in this batch.

**Comment by MFernflower** [comment]
Closing this issue - when you ship compounds just back reference this GHI @edwintse
