### ISSUE TITLE
The Phenylalaninol ether has been successfully synthesised

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/Series4#30]
The Phenylalaninol ether is key compound for the series originally proposed to investigate the ether chain length [(#254)](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/254). The synthesis of the compound was initially attempted by @JoannaUbels in 2014 by direct coupling of (_R_)-2-amino-3-phenylpropan-1-ol to the core, however the reaction was unsuccessful ([ELN](http://malaria.ourexperiment.org/triazolopyrazine_se/10883/)). Boc protection wasn't attempted due to time constrains. Most recently, this compound was picked up by Griffith Uni [(#523)](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/523) but again, time constraints meant the compound wasn't synthesised.

I have carried out the synthesis by Boc protecting the amine, SN2 displacement with the core and deprotecting under acidic conditions. The synthesis was done on both (_R_)- and (_S_)-enantiomers of the starting material.
![untitled wiley-3](https://user-images.githubusercontent.com/18062981/37134606-689040b8-22ed-11e8-8291-25b572d64f3e.jpeg)
ELN entries for [(_R_)](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/ODA5Ljl8MTUwOS82MjMvVHJlZU5vZGUvMTAyNzU1NTE4N3wyMDU1Ljk=)/[(_S_)](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/ODExLjJ8MTUwOS82MjQvVHJlZU5vZGUvNzI4NzQ3NTgxfDIwNTkuMg==) Boc protection, [(_R_)](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/ODE2LjR8MTUwOS82MjgvVHJlZU5vZGUvMTEwMTI2OTAzMnwyMDcyLjQ=)/[(_S_)](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/ODE5LjB8MTUwOS82MzAvVHJlZU5vZGUvMjc2NjY1NDE1OHwyMDc5LjA=) SN2 displacement and [(_R_)](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/ODE3Ljd8MTUwOS82MjkvVHJlZU5vZGUvMjIxNDQwNTk2NXwyMDc1Ljc=)/[(_S_)](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/ODIyLjl8MTUwOS82MzMvVHJlZU5vZGUvMjI1NzEzNDU3MHwyMDg4Ljk=) Boc deprotection.

(_R_)-Boc protected [1H](https://github.com/OpenSourceMalaria/Series4/files/1791905/1H.pdf),[13C](https://github.com/OpenSourceMalaria/Series4/files/1791909/13C.pdf),[19F](https://github.com/OpenSourceMalaria/Series4/files/1791911/19F.pdf) (pdfs attached).
(_S_)-Boc protected [1H](https://github.com/OpenSourceMalaria/Series4/files/1791963/1H.pdf) (pdfs attached).
(_R_)-free amine [1H](https://github.com/OpenSourceMalaria/Series4/files/1791944/1H.pdf) (pdfs attached).
(_S_)-free amine [1H](https://github.com/OpenSourceMalaria/Series4/files/1791976/1H.pdf) (pdfs attached).

n.b. NMRs of the free amines were done in MeOD so the amine signals are absent.
Currently awaiting further characterisation. Will need to also get optical rotation for these.

The 4 final compounds (both Boc protected and both free amines) will be sent off for biological evaluation in the next batch.

----------------------------------------------------------------------------------------------------
**Removed from the DCNYS section of the wiki**
Side chain derived from phenylalanine: GHI [254](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/254), [ELN](http://malaria.ourexperiment.org/triazolopyrazine_se/10883/), [OSM-S-261](http://malaria.ourexperiment.org/osm_procedures/10911/OSMS261.html), [Griffith Uni proposed synthesis](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/523)<br>
ClC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCH(N)CC4=CC=CC=C4)N32 InChI=1S/C20H18ClN5O/c21-16-8-6-15(7-9-16)20-25-24-18-11-23-12-19(26(18)20)27-13-17(22)10-14-4-2-1-3-5-14/h1-9,11-12,17H,10,13,22H2/t17-/m1/s1

<img src="https://github.com/OpenSourceMalaria/Series4/blob/master/Wiki%20Files/DCNYS/Phenylalaninol_ether.png" alt="Phenylalaninol ether analogues" width="150">

----------------------------------------------------------------------------------------------------
**Strings**

(_R_)-Boc protected
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC[C@H](NC(OC(C)(C)C)=O)CC4=CC=CC=C4)N32
InChI=1S/C26H27F2N5O4/c1-26(2,3)37-25(34)30-19(13-17-7-5-4-6-8-17)16-35-22-15-29-14-21-31-32-23(33(21)22)18-9-11-20(12-10-18)36-24(27)28/h4-12,14-15,19,24H,13,16H2,1-3H3,(H,30,34)
SDPYEXOSVNFLTG-UHFFFAOYSA-N

(_S_)-Boc protected
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC[C@@H](NC(OC(C)(C)C)=O)CC4=CC=CC=C4)N32
InChI=1S/C26H27F2N5O4/c1-26(2,3)37-25(34)30-19(13-17-7-5-4-6-8-17)16-35-22-15-29-14-21-31-32-23(33(21)22)18-9-11-20(12-10-18)36-24(27)28/h4-12,14-15,19,24H,13,16H2,1-3H3,(H,30,34)
SDPYEXOSVNFLTG-UHFFFAOYSA-N

(_R_)-free amine
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC[C@H](N)CC4=CC=CC=C4)N32
InChI=1S/C21H19F2N5O2/c22-21(23)30-17-8-6-15(7-9-17)20-27-26-18-11-25-12-19(28(18)20)29-13-16(24)10-14-4-2-1-3-5-14/h1-9,11-12,16,21H,10,13,24H2/t16-/m1/s1
FXPPGJNSMWQGRD-MRXNPFEDSA-N

(_S_)-free amine
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC[C@@H](N)CC4=CC=CC=C4)N32
InChI=1S/C21H19F2N5O2/c22-21(23)30-17-8-6-15(7-9-17)20-27-26-18-11-25-12-19(28(18)20)29-13-16(24)10-14-4-2-1-3-5-14/h1-9,11-12,16,21H,10,13,24H2/t16-/m0/s1
FXPPGJNSMWQGRD-INIZCTEOSA-N

**Comment by edwintse** [comment]
Compound has been removed from the DCNYS section (text copied over above).

**Comment by edwintse** [comment]
Closing, but will continue to upload the remaining data for completeness.

**Comment by mcoster** [comment]
I realise this is now closed, but belated congrats Ed!
