### ISSUE TITLE
Which compounds should we send for biofunctionalisation (batch III) April 2018?

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#32]
Scott Obach is happy to put a few more of our compounds through his biofunctionisation assay, which is great news. We previously sent a batch around July [last year ](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/513), and a second batch towards the end of last year - discussion on choice of compounds [here](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/529), and results [here](https://github.com/OpenSourceMalaria/Series4/issues/13). We will be including more of MMV693155 to repeat last years experiment that resulted in a <10 nM hit, to hopefully provide further insight into the [exact identity of this compound](https://github.com/OpenSourceMalaria/Series4/issues/24). We'd like to move quickly on this and aim to ship early next week.

The previous biosynthesis work is summarised below, and below that are the compounds we are selecting from this time. Input and suggestions appreciated - with reasoning, even more so!

### Previous biosyntheses
![previous pfizer work mar18](https://user-images.githubusercontent.com/30584472/38066507-ffd3eefe-3353-11e8-9a79-6a68298d24d4.png)
[Previous Pfizer Work Mar18.zip](https://github.com/OpenSourceMalaria/Series4/files/1858392/Previous.Pfizer.Work.Mar18.zip)

### Choice of next batch from these compounds
![dundee results 260218](https://user-images.githubusercontent.com/30584472/38066552-32722646-3354-11e8-8c83-b7ed0ac16077.png)
![decdundee](https://user-images.githubusercontent.com/30584472/38066564-431198d8-3354-11e8-8e6b-eee9fd3b3800.jpg)
[DecDundee.zip](https://github.com/OpenSourceMalaria/Series4/files/1858393/DecDundee.zip)
[Dundee Results 260218.zip](https://github.com/OpenSourceMalaria/Series4/files/1858394/Dundee.Results.260218.zip)

**Comment by david1597** [comment]
I'd suggest @maratsydney's recent OSM-S-525, as the RHS structure is different to anything we've looked at previously, and OSM-S-525 itself is a very potent starting point. And/ore OSM-S-502 for a similar structural reason.

**Comment by MFernflower** [comment]
The Pfizer phenolic compound to see if we get carboxylic acid 
formation and/or quinone formation!!!!  @david1597

**Comment by mattodd** [comment]
My votes:
The original alcohol, as a repeat, given #33 
The phenolic "Pfizer compound" David has synthesised, OSM-S-412, to see if this is a compound en route to the mystery compound
Marat's compound OSM-S-525, as a new highly potent molecule
The Norcross compound with a little activity OSM-S-518
Tha's compound OSM-S-106 from Series 3, for interest

That's it, but backups could be OSM-S-502 and OSM-S-497

**Comment by MFernflower** [comment]
I'm very curious to see if we will get funky oxidation products from Marat's indole hit - Def should send like 15 milligrams out

**Comment by david1597** [comment]
The following five compounds were shipped 6/4/18.

[ELN link](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjQ3LjB8MzAxNzEvMTkwL1RyZWVOb2RlLzEzMzU0MzIwMzl8NjI3LjA=). 

![pfizer april 2018 compounds sent](https://user-images.githubusercontent.com/30584472/38406083-c1e5e5f2-39b6-11e8-9df7-2376fea5c007.jpg)

[Pfizer April 2018 Compounds Sent.zip](https://github.com/OpenSourceMalaria/Series4/files/1882912/Pfizer.April.2018.Compounds.Sent.zip)


Code | Batch | Amount | MW | Formula | SMILES | InChI | InChIKey
-- | -- | -- | -- | -- | -- | -- | --
OSM-S-106 | MNB 6-7 | 1.97 mg | 306.4 | C12H10N4O2S2 | NC1=C2C(C=C(C3=CC(S(N)(=O)=O)=CC=C3)S2)=NC=N1 | InChI=1S/C12H10N4O2S2/c13-12-11-9(15-6-16-12)5-10(19-11)7-2-1-3-8(4-7)20(14,17)18/h1-6H,(H2,13,15,16)(H2,14,17,18) | MQMXDJVOZKMSNT-UHFFFAOYSA-N
OSM-S-353 | EGT 198-4 | 2.97 mg | 412.4 | C21H18F2N4O3 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C4=CC=CC=C4)CO)N32 | InChI=1S/C21H18F2N4O3/c22-21(23)30-17-8-6-15(7-9-17)20-26-25-18-10-24-11-19(27(18)20)29-13-16(12-28)14-4-2-1-3-5-14/h1-11,16,21,28H,12-13H2 | MGANJQKOPZQELF-UHFFFAOYSA-N
OSM-S-412 | DGS 43-4 | 2.02 mg | 428.4 | C21H18F2N4O4 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)C4=CC=C(O)C=C4)N32 | InChI=1S/C21H18F2N4O4/c22-21(23)31-17-7-3-14(4-8-17)20-26-25-18-9-24-10-19(27(18)20)30-12-15(11-28)13-1-5-16(29)6-2-13/h1-10,15,21,28-29H,11-12H2 | BCDILCAJSSYWKE-UHFFFAOYSA-N
OSM-S-518 | MK 048-1 | 3.14 mg | 395.4 | C18H17F4N5O | FC1=CC(CCOC2=CN=CC3=NN=C(N4CCC(F)(F)CC4)N32)=CC=C1F | InChI=1S/C18H17F4N5O/c19-13-2-1-12(9-14(13)20)3-8-28-16-11-23-10-15-24-25-17(27(15)16)26-6-4-18(21,22)5-7-26/h1-2,9-11H,3-8H2 | QEKAFCQAHVHCHN-UHFFFAOYSA-N
OSM-S-525 | MK 035-1 | 2.02 mg | 391.4 | C21H15F2N5O | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C5C(NC=C5)=C4)N32)=CC=C1F | InChI=1S/C21H15F2N5O/c22-16-4-1-13(9-17(16)23)6-8-29-20-12-24-11-19-26-27-21(28(19)20)15-3-2-14-5-7-25-18(14)10-15/h1-5,7,9-12,25H,6,8H2 | VHFREJHLTSVZGA-UHFFFAOYSA-N

**Comment by cdsouthan** [comment]
Good  stuff @david1597 but just for the record, how much of  the batches do you keep back?  Also do/have you ever asked Dundee for occasional re-tests?

**Comment by david1597** [comment]
@cdsouthan it varies quite a bit from compound to compound. There are 200 mg+ of OSM-S-353 remaining, only about 25 mg of OSM-S-412 and smaller amounts than that of OSM-S-518 and 525. We essentially ship the 2 mg that Dundee require, leaving back whatever we made.

Generally we have not done many re-tests. There was one in the December set (#10): OSM-S-369 (MMV897698). The first testing from Dec 2016 gave 0.251 µM (average of two runs, although those two runs were a little different from one another: 0.164 and 0.338 µM), whilst Dec 2017 gave 0.248 µM (just one run so far - we're still waiting on the second run of the Dec 2017 set, it has been done but the data has been consumed by a black hole...the MMV data people are on the case and we'll hopefully have it soon). In this particular case, I believe it was two separate syntheses, and not just a re-run of the same batch of compound.

**Comment by MFernflower** [comment]
Just an FYI for anyone who wants it: Exposed indoles are known to do weird stuff in the liver: https://www.sciencedirect.com/topics/medicine-and-dentistry/skatole @david1597

**Comment by drc007** [comment]
@MFernflower I suspect that is a 3-alkyl indole specific effect, oxidation of the alkyl can lead to 3‐methyleneindolenine derivatives which are highly reactive. That said there are plenty of 3-alkyl indole drugs.

**Comment by MFernflower** [comment]
So the compound marat made should be relatively nontoxic @drc007

>

**Comment by drc007** [comment]
At least not toxic via that mechanism.

**Comment by david1597** [comment]
Closing this issue as the [compounds ](https://github.com/OpenSourceMalaria/Series4/issues/32#issuecomment-379160503)were shipped last month and are now with the Pfizer team who will work through them as they get the time and availability. New issues will be created as results come back.

**Comment by mattodd** [comment]
To avoid orphaning, link installed on [new biofunctionalisation page on wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Biofunctionalisation) (which needs more, obv).
