### ISSUE TITLE
Questions about LHS benzene ring halogenation 

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/Series4#34]
**Has the effects of halogenation of the phenylethanol LHS fragment of the S4 drugs been studied?** I have seen molecules made with various ring halogenation patterns - including the rather oily 4,3-difluorophenylethanol

I propose we make the same compound with each of the commonly used substitutions to see if potency can be changed by playing with the pattern and to find the pattern with the most benefits:  (see example image) 
![untitled](https://user-images.githubusercontent.com/3164942/38399192-c9c9985e-3916-11e8-9687-e4ae07c40e30.png)

**Forgive me if this has already been done before** @mattodd @david1597 

SMILES STRINGS:
FC1=CC=C(CCOC2=CN=CC3=NN=C(N23)C2=CC=C(C=C2)C#N)C=C1F
FC1=CC=C(CCOC2=CN=CC3=NN=C(N23)C2=CC=C(C=C2)C#N)C=C1
FC1=CC(CCOC2=CN=CC3=NN=C(N23)C2=CC=C(C=C2)C#N)=CC=C1
N#CC1=CC=C(C=C1)C1=NN=C2C=NC=C(OCCC3=CC=CC=C3)N12

Predictions done by SwissADME:

![swissadme](https://user-images.githubusercontent.com/3164942/38462486-f6989682-3ab5-11e8-94fa-9ee5daeb58cc.png)

**Comment by mattodd** [comment]
Hi @MFernflower - check the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Pyrazine-Side-Chain-Modifications---Ethers). There have been quite a few compound examining this, but obviously all quite greasy. Sensitivity to small variations, for sure, but it seems to me we would come back to this once we have potent compounds that have lower overall logP. Close this issue if that's all.
(the big scheme of analogs on that wiki page, which is no longer up to date, was not rendering correctly, being dragged in from the old wiki site. I've fixed that by uploading the file to this repo.)
