### ISSUE TITLE
Two minor issues re liver stage data for Series 4

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series4#4]
I've updated the [wiki section on liver stage potency](https://github.com/OpenSourceMalaria/Series4/wiki/Liver-Stage), and inserted a section on this into [the paper](http://tinyurl.com/OSM-S4-Paper1). I've added relevant files to the paper repo _via_ a [pull request](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/pull/13).

![liver schizont data for s4](https://user-images.githubusercontent.com/4386101/29565720-6bb8a4f0-878a-11e7-90f0-fe25c5e662f0.png)

Two unresolved items:

1) One of the compounds evaluated was [the frontrunner that was ultimately resolved](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/470). We have some left of the enantiomers. [Once we're clear what's what](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/517#issuecomment-324001899), it might be possible/sensible to use these samples to see if the liver stage potency, weak though it is, arises from one rather than the other. Have asked Elizabeth Winzeler if this could be done.

2) [Way back](http://malaria.ourexperiment.org/triazolopyrazine_se/8912) it was suggested that these compounds should be sent for evaluation _vs._ hypnozoites. I will chase whether this was ever done.

**Comment by MFernflower** [comment]
@mattodd Would it be possible to send off some of the SF5 compound for hypnozo eval?

**Comment by mattodd** [comment]
Yes, but I don't see a major need for it (i.e., cost-benefit). The potential advantages you mention [here](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/517#issuecomment-322273751) for this compound are speculative, unless you have reasons for them?

**Comment by MFernflower** [comment]
Indeed they are pretty speculative and based off of things I had read in the past - would OCHF3 make a better replacement for SF5 and OCHF2? I'm sorry if it's a obvious question as I have not seen the wiki in a while!

**Comment by MFernflower** [comment]
Sorry to post in another comment but wouldn't the most logical thing to do if we do indeed send off for hypnozo eval would be to send some of David's OSM-S-412 (when it's made) and some inactive compound as a control? I know it's only a sample size of one but if we can verify if the alcohol tweaks are as good in liver stage as in blood stage it would be a confirmation that we should indeed head down the alcohol/lactone/ketone route ?

@mattodd

**Comment by mbhebhe** [comment]
Three compounds from Series 4 (shown below) were shipped last week to UCSD for liver stage testing

![image](https://user-images.githubusercontent.com/26862286/32202505-65ee09f6-be31-11e7-9946-8081cfec931b.png)

MMV # | SMILES | InChl | InChl Key
-- | -- | -- | --
MMV897709 | FC(C=CC(C(COC1=CN=CC2=NN=C(N21)C3=CC=C(C=C3)C#N)OC)=C4)=C4F | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3 | PERKBMZWWUEZNJ-UHFFFAOYSA-N
MMV1557952 | FC(C=CC([C@@H](COC1=CN=CC2=NN=C(N21)C3=CC=C(C=C3)C#N)OC)=C4)=C4F | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3/t18-/m1/s1 | PERKBMZWWUEZNJ-GOSISDBHSA-N
MMV1557951 | FC(C=CC([C@H](COC1=CN=CC2=NN=C(N21)C3=CC=C(C=C3)C#N)OC)=C4)=C4F | InChI=1S/C21H15F2N5O2/c1-29-18(15-6-7-16(22)17(23)8-15)12-30-20-11-25-10-19-26-27-21(28(19)20)14-4-2-13(9-24)3-5-14/h2-8,10-11,18H,12H2,1H3/t18-/m0/s1 | PERKBMZWWUEZNJ-SFHVURJKSA-N

**Comment by mattodd** [comment]
Tying up loose ends for paper. All of this issue is adequately linked in the wiki section on liver stage.
For the paper, the more recent work was carried out by Sabine Ottilie, Jenya Antonova and Korina Eribez. Attached is the shipping note with the compounds that were evaluated, just for the record.


[UCSD Oct 2017 compounds.docx](https://github.com/OpenSourceMalaria/Series4/files/6631775/UCSD.Oct.2017.compounds.docx)
