### ISSUE TITLE
The side-products formed during The OHOH synthesis

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#41]
My recent [attempted syntheses](#36 ) of The OHOH did not proceed cleanly and resulted in a number of products.

It looks like one of these products may be this epoxide. Expected mass is 410.1. Although the NMR is not completely clean there are two clear pairs of doublets. One pair around 4.5-5 ppm which correspond to the ether CH2. And the pair below 3 ppm which I am ascribing to the terminal epoxide. I observed this product in more than one of the attempted reactions. I am currently purifying these further and will then obtain further characterisation. 

![image](https://user-images.githubusercontent.com/30584472/39462596-f4b1bdc8-4d55-11e8-8e36-c3ea17ee6ec3.png)
![image](https://user-images.githubusercontent.com/30584472/39462483-509606d6-4d55-11e8-92c0-52424655bfd8.png)
![image](https://user-images.githubusercontent.com/30584472/39462589-edbe756a-4d55-11e8-9ef3-75147a366c0e.png)

**Comment by MFernflower** [comment]
This is more of a lemons to lemonade thing but maybe you can open the epoxy ring to a diol and couple resulting diol to 1,3 dichloropropane thus giving a dioxocycle? @david1597

**Comment by david1597** [comment]
Further attempts to purify this suspected epoxide were not successful. Stability appears to be an issue and after storage in the fridge it appeared to have significantly degraded.

This product, and the other unwanted reactions occurred when attempting the substitution on the unprotected triol. This can be circumvented by protecting the triol - see the [wiki ](https://github.com/OpenSourceMalaria/Series4/wiki/Synthesis-of-Benzylic-Functionalised-Ether-Linked-Series) for a short summary on a successful route to the final compound.

@MFernflower to answer your question about was any desired product obtained - yes, there appeared to be so by mass spec of the crude reaction mixture but I could not obtain any following purification. The proposed epoxy compound was not the only thing, there were many peaks obtained from chromatography but the epoxide was the only one to give a clean NMR and hint at its structure.

**Comment by MFernflower** [comment]
All relevant information has been installed to the wiki - closing this issue
