### ISSUE TITLE
Selection of Representative Compounds for Gametocyte Assay

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/Series4#5]
With the [Series 4 paper in progress](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/532), we need to tie up a loose end related to whether Series 4 has gametocyte stage activity. ([Wiki section](https://github.com/OpenSourceMalaria/Series4/wiki/Gametocyte-Stage)). The possibility of gametocyte activity in this series has been [discussed](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/397) and seems reasonable to check for. Not a priority for the series, but something important to check.

Which compounds to send? I'd suggest two potent actives and one inactive control from the [frontrunners](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/400)?

@david1597 @edwintse we have stocks available, right? I will check on which lab might be willing to run these.

**Comment by cdsouthan** [comment]
I suggest just make that two inactives, for symmetry...  n.b. if the two pairs are at least slightly divergent in chemical properties (even if  they are all same series)  but similar as pairs (i.e. the inactive as structurally close to the potent as possible).  Note also the lab should also run a standard parasite assay in // with the gametocyte (i.e. same lab same week) and do enough replicates for a convincing +/- SD

**Comment by mattodd** [comment]
OK, Paul Willis says "A PfATP4 inhibitor will inhibit male gametocyte exflagellation so I would recommend sending the compounds to Imperial for the DGFA, within the MMV network" - that'll be the target of the shipment. Two actives, two inactives. I'm not sure about the absolute requirement for concurrent standard blood stage assay @cdsouthan - I can ask, but we're pretty happy with the potencies of the oft-tested compounds and there would be, I assume, an internal assay control. I'll see what they say.

**Comment by david1597** [comment]
Two actives and two inactives, with some structural similarity between the pairs:

We have sufficient stocks, so are these the four to send?

![sep17 compounds to send for gametocyte assay](https://user-images.githubusercontent.com/30584472/30463588-f79f69b2-9a0f-11e7-937f-fed6769d3924.jpg)

**Comment by mattodd** [comment]
Yes, these look good to me @david1597 . Great. This is the kind of thing you had in mind @cdsouthan ? Will clear this with MMV and Imperial if so and we can ship. Will ask about concurrent blood stage potency assay.

**Comment by cdsouthan** [comment]
Yes,  but as ever,  the more controls you include the better  e.g.  another pair from someone else's directly verified PfATP4 inhibitor series?

**Comment by david1597** [comment]
We don't have sufficient quantities of MMV693155 to send (see #6), and so we propose to send MMV68896 instead. Not as potent, but a better structural match to it's partner so perhaps a better choice anyway.

![updated sep17 compounds to send for gametocyte assay](https://user-images.githubusercontent.com/30584472/30728722-6625db7c-9f9d-11e7-87db-0ce92eb6c143.jpg)

**Comment by david1597** [comment]
The following four compounds were shipped 25/9/17:

![sep17 icl](https://user-images.githubusercontent.com/30584472/30787834-510bc302-a1d5-11e7-8f41-4ed169b123bb.jpg)

This issue is now closed. Results will be discussed in a new issue and posted [here ](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/OTQuOXwzMDE3MS83My9UcmVlTm9kZS80MDk4MzgwOTk5fDI0MC44OTk5OTk5OTk5OTk5OA==
)in the ELN.
