### ISSUE TITLE
Series 4 Synthesis Update - June 2018

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#51]
We're at a busy time with synthesis in series 4. This is the collective work of many contributors. Those active in the lab include @edwintse, @maratsydney, @david1597, @Plebellec and @CamilleHauguel, along with @mattodd, @mcoster, @MedChemProf and @alintheopen with their students.

One thread is exploration of the RHS following a promising [indole ](https://github.com/OpenSourceMalaria/Series4/issues/26#issuecomment-375812826)compound obtained from some Suzuki chemistry. This was followed up with many more [analogues ](#39)in April. A further [set ](https://github.com/OpenSourceMalaria/Series4/issues/39#issuecomment-393358625)will be sent for testing next week. 

On the LHS, the [Pfizer ](#33 )compound continues to be a lead. A [chemical synthesis](#36) of the original compound and a couple more of these 'OHOH' compounds have been made and will be sent for testing next week. A number of related [2-phenyl-propan-1-ol's ](#3 )are being actively explored, and related [benzylic amine](#50) compounds are also now proposed. 

Also currently active are ethers and amines in the [5-position](#46). [Ethers ](#49)have already been successful. The [amine](#47) work is still active.

Other new linkers on the pyrazine that do not yet exist in our library are also being investigated including [carbamates and ureas](#43).

A good number of compounds from the [DCNYS ](https://github.com/OpenSourceMalaria/Series4/wiki/Desirable-Compounds-Not-Yet-Synthesised)have been successfully made recently: the [HERG evador](#22), the [Nemesis](#38) and the [phenylalaninol](#30 ).

A further carborane compound has been made, following a highly potent [one ](#8) from last year.

Undergraduate classes have also been actively contributing. The Sydney [2018 SSP](https://github.com/OpenSourceMalaria/Series4/issues/39#issuecomment-393358625) class have been working on a set of compounds and the Griffith [GRIDD](#43) team are functionalising the 8 position.

And lastly, it's not just humans involved in the synthesis effort. Further [biosynthesis ](#32)is also underway at Pfizer. 

![image](https://user-images.githubusercontent.com/30584472/41074966-e0cd5e92-6a4d-11e8-8409-7d55b4e66224.png)

**Comment by MFernflower** [comment]
Friendly reminder: This thread needs updating as many of these compounds have been completed and have been send out for testing as per #54

**Comment by MFernflower** [comment]
Close as per #54
