### ISSUE TITLE
April 2018 Dundee Potency Results

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#56]
At least two repeats for each compound have now been run. I'm starting a new issue for these results here as the original [thread ](#39 )is now at 60 comments and overcrowded with a number of discussions.

Averaged values are indicated in the figure. Individual repeat values are tabulated below that. Some compounds have significantly different values for the two repeats, eg. OSM-S-486 at 1.92 and 0.38 µM. It is likely that further repeats will be performed for these select compounds. 

![april dundee results](https://user-images.githubusercontent.com/30584472/43172437-a10b82dc-8ff2-11e8-87d4-538c7f849f58.jpg)

MMV   number | OSM number | Internal number | Potency 1 | Potency 2 | Potency 3 | Potency 4 | Average
-- | -- | -- | -- | -- | -- | -- | --
MMV1579341 | OSM-S-525 | MK035-2 | 0.087 | 0.167 |   |   | 0.13
MMV1580421 | OSM-S-532 | DGS 33-1 | 0.03 | 0.088 |   |   | 0.06
MMV1580422 | OSM-S-533 | DGS 32-1 | 0.347 | 0.416 |   |   | 0.38
MMV1580423 | OSM-S-535 | EGT 306-1 | 9.285 | 7.845 |   |   | 8.57
MMV1580424 | OSM-S-536 | EGT 307-1 | 10.26 | 23.01 |   |   | 16.64
MMV1580426 | OSM-S-538 | EGT 311-1 | 1.418 | 3.108 |   |   | 2.26
MMV1580425 | OSM-S-537 | EGT 308-1 | 5.65 | 14.32 |   |   | 9.99
MMV1580427 | OSM-S-542 | MK031-2a | >25.11 | >25.11 |   |   | >25
MMV1580428 | OSM-S-543 | MK031-2b | >25.11 | 18.5 |   |   | 18.50
MMV1580429 | OSM-S-544 | MK055-1 | >25.11 | >25.11 |   |   | >25
MMV1580430 | OSM-S-545 | MK062-1 | 6.835 | 7.214 |   |   | 7.02
MMV1580431 | OSM-S-546 | MK063-1 | 0.522 | 0.346 |   |   | 0.43
MMV1580432 | OSM-S-547 | MK064-1 | 4.699 | 5.195 |   |   | 4.95
MMV1580433 | OSM-S-548 | MK065-1 | 0.031 | 0.059 |   |   | 0.05
MMV1580434 | OSM-S-549 | MK067-1 | 1.538 | 4.063 |   |   | 2.80
MMV1580435 | OSM-S-550 | MK068-1 | 0.035 | 0.253 |   |   | 0.14
MMV1580436 | OSM-S-551 | MK069-1 | >25.11 | >25.11 |   |   | >25
MMV1580439 | OSM-S-557 | MK074-1 | 0.036 | 0.101 |   |   | 0.07
MMV1580438 | OSM-S-553 | MK053-1 | 0.351 | 1.601 |   |   | 0.98
MMV1580440 | OSM-S-486 | DGS 51-2 | 1.92 | 0.379 |   |   | 1.15
MMV1580441 | OSM-S-554 | EGT 324-1 | >25.11 | >25.11 |   |   | >25
MMV1580442 | OSM-S-555 | EGT 325-1 | >25.11 | >25.11 |   |   | >25

- original data plots are in my [ELN](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MzgyLjJ8MzAxNzEvMjk0L1RyZWVOb2RlLzI0ODE1NzQ4NTF8OTcwLjE5OTk5OTk5OTk5OTk=)
- the above potency summary figure is on the Biological Data Not Yet Incorporated [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections)
- data has been entered into the [master list](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618)

**Comment by MFernflower** [comment]
Do you think the RHS para-alkyl series is worth pursuing? Perhaps p-methyl and p-isopropyl? if the required boronic acids are in lab stock? @david1597

**Comment by david1597** [comment]
@MFernflower No, at least not those exact compounds. clogP is predicted at 4.9 and 5.9 (ChemDraw) respectively. Preference is that any future compounds we make in that series offer an improvement in terms of the other parameters - above potency - that we're looking at.

Any further discussion for future compounds relating to that RHS can go in a new issue otherwise this issue will end up like the previous 60 comment monster we had previously.

**Comment by mattodd** [comment]
Agreed. Thanks for posting @david1597 . For completeness could you please post the Chemdraw and pic files somewhere, either on GH in this repo or on your ELN? Saves people re-drawing. Once we incorporate into the wiki and into forward analog planning we can close this issue, but these data need to be considered first. Will include the actives in my talk here tomorrow, to see what the medchem crowd here in Ljubljana say.

**Comment by mattodd** [comment]
Assigning to @edwintse to fold these data into the wiki as part of S4 paper preparations. All relevant chemdraws should be available for editing.

**Comment by edwintse** [comment]
Closing. Compounds folded into the wiki.
