### ISSUE TITLE
Possible enantioselective synthetic route to the OHOH compounds

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#58]
We may wish to pursue an enantioselective synthesis of the OHOH compounds at some point in the future if they show promise and if it is favourable to chiral resolution.

A proposed route to obtain the chiral tertiary alcohol required involves the catalytic enantioselective desymmetrising benzoylation of meso-2-substituted glycerols - the intermediates used in the synthesis of the OHOH compounds. Two papers show how chiral tertiary alcohols can be formed in this way with high enantioselectivity - one using a bisoxazoline-copper complex and the other an imine copper chloride complex. (These papers were actually the literature I followed to get those OHOH intermediates).

Paper 1: [Chiral imine copper chloride-catalyzed enantioselective desymmetrization of 2-substituted 1,2,3-propanetriols](http://www.pnas.org/content/104/5/1471)

Paper 2: [Enantioselective Synthesis of Tertiary Alcohols by the Desymmetrizing Benzoylation of 2-Substituted Glycerols](https://onlinelibrary.wiley.com/doi/epdf/10.1002/anie.200604977)

![image](https://user-images.githubusercontent.com/30584472/43238842-43e2f4e6-90d3-11e8-91a1-b0cf2886f8d0.png)

This info is also on the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Chirality-Stereogenic-Centres-in-This-Series#enantioselective-approaches), along with a previous suggestion for an [enantioselective synthesis of an alcohol arm](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/167).

Posting this in an issue in case of any immediate questions or comments. It will be closed shortly otherwise, with the wiki link serving as a record.

**Comment by MFernflower** [comment]
Just curious - are the copper binding ligands commercially available or need to be made de-novo? I don't have access to the full paper @david1597

**Comment by MFernflower** [comment]
Closing this as relevant data has been added to the wiki
