### ISSUE TITLE
Resynthesis of more stock of MMV693155

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#6]
We only have ~2 mg of MMV693155, as noticed when preparing samples to send for the [gametocyte assay](https://github.com/OpenSourceMalaria/Series4/issues/5). 

Posting this issue here as a reminder to synthesise more. We'd like to have adequate stocks of any promising compounds so as they are always available when we wish to send compounds out, or the compounds are requested by other interested parties.

![mmv693155](https://user-images.githubusercontent.com/30584472/30728560-3380b1c0-9f9c-11e7-88d9-e07f638491aa.jpg)

**Comment by edwintse** [comment]
Currently working on this [here](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/Nzc3LjR8MTUwOS81OTgvVHJlZU5vZGUvMjI1NDk5OTIxN3wxOTczLjM5OTk5OTk5OTk5OTk=
).

**Comment by david1597** [comment]
The re-synthesis was completed by Ed. We currently have a few hundred mg of compound. ELN link through Ed's post above and associated EGT 198-3 and EGT 198-4.
