### ISSUE TITLE
Compounds sent for biological testing Nov 2018

### ISSUE THREAD

**Issue by mbhebhe** [OpenSourceMalaria/Series4#62]
Here is list of compounds that we have sent to Dundee. 

Series 3:
- USyd samples:
OSM-S-606 is a product of the bromination of pyrrole occurring at the 7th position.
OSM-S-137 (slightly active at 1.7 uM) was re-synthesized for sending to Kansas State Uni and UNC for kinome testing.
OSM-S-145 was synthesised but not tested and came across it in the fridge.
OSM-S-649 (carboxylic analogue of OSM-S-106) that was [suggested](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/561) by @drc007 
- SGS-UNC samples to be sent soon.
These molecules were made by Alfredo Picado from [SGS-University of North Carolina](https://github.com/OpenSourceMalaria/Series3/issues/8). They are similar to our Series 3 compounds. We will see if they have any activity. 

Series 4:
- First in Series 4 5-substituted amines (made by @david1597 #47 ) + two molecules of 5- and 6-substituted amines (OSM-S-631 and OSM-S-634 made by @maratsydney)
- OHOH compound (made by @david1597 #36 ) + some other compounds (including the RHS benzimidazole proposed by @MFernflower). 
- 8-Substituted compounds that originated from tele-substitution reaction studies. #46
- Reference sample (OSM-S-369)  as discussed [before](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/572).

![image](https://user-images.githubusercontent.com/26862286/48593966-1cfbb880-e9a3-11e8-9a9f-fe798f8e9527.png)
![image](https://user-images.githubusercontent.com/26862286/48593983-2b49d480-e9a3-11e8-9340-65c969fa8219.png)
![image](https://user-images.githubusercontent.com/26862286/48594006-37359680-e9a3-11e8-9a3c-d6769e00a3b5.png)
![image](https://user-images.githubusercontent.com/26862286/48594030-4ddbed80-e9a3-11e8-95d1-61fbc827b283.png)
![image](https://user-images.githubusercontent.com/26862286/48594044-5a604600-e9a3-11e8-8f9c-11ba6e7d257f.png)
[2018 November Dundee Compounds list.zip](https://github.com/OpenSourceMalaria/Series4/files/2587770/2018.November.Dundee.Compounds.list.zip)
----------------------------------------------------------------------------------------------------
MMV   Number | SMILES | InChI | InChI Key
-- | -- | -- | --
MMV1634420 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC(NCCC4=CC=CC=C4)=CN32| InChI=1S/C20H17F2N5O/c21-20(22)28-16-8-6-15(7-9-16)19-26-25-18-12-24-17(13-27(18)19)23-11-10-14-4-2-1-3-5-14/h1-9,12-13,20,23H,10-11H2 | OPITXRFBTTVRFQ-UHFFFAOYSA-N
MMV1634421 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(NCCC4=CC=C(OC)C(OC)=C4)N32 | 	InChI=1S/C22H21F2N5O3/c1-30-17-8-3-14(11-18(17)31-2)9-10-26-19-12-25-13-20-27-28-21(29(19)20)15-4-6-16(7-5-15)32-22(23)24/h3-8,11-13,22,26H,9-10H2,1-2H3	| VDXJYWCEOGLVSA-UHFFFAOYSA-N
MMV1634422	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(NC[C@@H](O)C4=CC=CC=C4)N32 |  InChI=1S/C20H17F2N5O2/c21-20(22)29-15-8-6-14(7-9-15)19-26-25-18-12-23-11-17(27(18)19)24-10-16(28)13-4-2-1-3-5-13/h1-9,11-12,16,20,24,28H,10H2/t16-/m1/s1	| MOIHJTIFLGFROE-MRXNPFEDSA-N
MMV1634423	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(NC[C@H](O)C4=CC=CC=C4)N32	| InChI=1S/C20H17F2N5O2/c21-20(22)29-15-8-6-14(7-9-15)19-26-25-18-12-23-11-17(27(18)19)24-10-16(28)13-4-2-1-3-5-13/h1-9,11-12,16,20,24,28H,10H2/t16-/m0/s1	| MOIHJTIFLGFROE-INIZCTEOSA-N
MMV1634424	| FC(OC1=CC=C(C2=NN=C3C=NC=C(NCC4=CC=CC=C4)N32)C=C1)F | 	InChI=1S/C19H15F2N5O/c20-19(21)27-15-8-6-14(7-9-15)18-25-24-17-12-22-11-16(26(17)18)23-10-13-4-2-1-3-5-13/h1-9,11-12,19,23H,10H2	| GWROJQFCRZTYNJ-UHFFFAOYSA-N
MMV1634425	| COC(C=C1)=CC=C1C2=NN=C3C=NC=C(NCCC4=CC=CC=C4)N32 | 	InChI=1S/C20H19N5O/c1-26-17-9-7-16(8-10-17)20-24-23-19-14-21-13-18(25(19)20)22-12-11-15-5-3-2-4-6-15/h2-10,13-14,22H,11-12H2,1H3	| BQLWJIPILDPOQZ-UHFFFAOYSA-N
MMV1634426	| NC(C=C1)=CC=C1C(CO)COC2=CN=CC(N23)=NN=C3C4=CC=C(OC(F)F)C=C4 | 	InChI=1S/C21H19F2N5O3/c22-21(23)31-17-7-3-14(4-8-17)20-27-26-18-9-25-10-19(28(18)20)30-12-15(11-29)13-1-5-16(24)6-2-13/h1-10,15,21,29H,11-12,24H2	| DWSRIPSLMMOTPD-UHFFFAOYSA-N
MMV1634427	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)C4=CC=C(NC)C=C4)N32 | 	InChI=1S/C22H21F2N5O3/c1-25-17-6-2-14(3-7-17)16(12-30)13-31-20-11-26-10-19-27-28-21(29(19)20)15-4-8-18(9-5-15)32-22(23)24/h2-11,16,22,25,30H,12-13H2,1H3	| YOPBTMOYZOBXTE-UHFFFAOYSA-N
MMV1634428	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CS4)N32 | 	InChI=1S/C18H14F2N4O2S/c19-18(20)26-13-5-3-12(4-6-13)17-23-22-15-10-21-11-16(24(15)17)25-8-7-14-2-1-9-27-14/h1-6,9-11,18H,7-8H2	| RMZMYNQAPRIYLW-UHFFFAOYSA-N
MMV1634429	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C)C4=CC=CC=C4)N32 | 	InChI=1S/C21H18F2N4O2/c1-14(15-5-3-2-4-6-15)13-28-19-12-24-11-18-25-26-20(27(18)19)16-7-9-17(10-8-16)29-21(22)23/h2-12,14,21H,13H2,1H3	| YELIMUUXHYJNPF-UHFFFAOYSA-N
MMV1634430	| FC(C=C1)=C(F)C=C1CCOC2=CN=CC3=NN=C(OCC4=CN=CC=C4)N32 | 	InChI=1S/C19H15F2N5O2/c20-15-4-3-13(8-16(15)21)5-7-27-18-11-23-10-17-24-25-19(26(17)18)28-12-14-2-1-6-22-9-14/h1-4,6,8-11H,5,7,12H2	| KXBYYTPVSDHELS-UHFFFAOYSA-N
MMV1634431	| FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC5=C(C=C4)N=CN5)N32)=CC=C1F | 	InChI=1S/C20H14F2N6O/c21-14-3-1-12(7-15(14)22)5-6-29-19-10-23-9-18-26-27-20(28(18)19)13-2-4-16-17(8-13)25-11-24-16/h1-4,7-11H,5-6H2,(H,24,25)	| OKICKLNNAMYKHW-UHFFFAOYSA-N
MMV1634432	| COC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32 | 	InChI=1S/C20H18N4O2/c1-25-17-9-7-16(8-10-17)20-23-22-18-13-21-14-19(24(18)20)26-12-11-15-5-3-2-4-6-15/h2-10,13-14H,11-12H2,1H3	| FOEYJDQRLPZFOG-UHFFFAOYSA-N
MMV1634433	| O=[[N+]](C(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32)(C(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32)[O-] |  	InChI=1S/C19H15N5O3/c25-24(26)16-8-6-15(7-9-16)19-22-21-17-12-20-13-18(23(17)19)27-11-10-14-4-2-1-3-5-14/h1-9,12-13H,10-11H2	| XKYBKXJISXRHEZ-UHFFFAOYSA-N
MMV1634434	| COC(C=C1)=CC=C1C2=NN=C3C=NC=C(SCCC4=CC=CC=C4)N32 | 	InChI=1S/C20H18N4OS/c1-25-17-9-7-16(8-10-17)20-23-22-18-13-21-14-19(24(18)20)26-12-11-15-5-3-2-4-6-15/h2-10,13-14H,11-12H2,1H3	| XKLPATLXLSUHOI-UHFFFAOYSA-N
MMV1634435	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)(CO)C4=CC=CC=C4)N32 | 	InChI=1S/C22H20F2N4O4/c23-21(24)32-17-8-6-15(7-9-17)20-27-26-18-10-25-11-19(28(18)20)31-14-22(12-29,13-30)16-4-2-1-3-5-16/h1-11,21,29-30H,12-14H2	| JCCXTGDCGIGQKA-UHFFFAOYSA-N
MMV1634436	| C1(OCCC2=CC=CC=C2)=NC=CN3C1=NN=C3C4=CC=CC=C4 | 	InChI=1S/C19H16N4O/c1-3-7-15(8-4-1)11-14-24-19-18-22-21-17(23(18)13-12-20-19)16-9-5-2-6-10-16/h1-10,12-13H,11,14H2	| BKUOBYRSGGKOSW-UHFFFAOYSA-N
MMV1634437	| COC(C=C1)=CC=C1C2=NN=C3C(OCCC4=CC=CC=C4)=NC=CN32 | 	InChI=1S/C20H18N4O2/c1-25-17-9-7-16(8-10-17)18-22-23-19-20(21-12-13-24(18)19)26-14-11-15-5-3-2-4-6-15/h2-10,12-13H,11,14H2,1H3	| KNDAUWHMGBUKCB-UHFFFAOYSA-N
MMV1634438	| O=[[N+]](C(C=C1)=CC=C1C2=NN=C3C(OCCC4=CC=CC=C4)=NC=CN32)(C(C=C1)=CC=C1C2=NN=C3C(OCCC4=CC=CC=C4)=NC=CN32)[O-] |  	InChI=1S/C19H15N5O3/c25-24(26)16-8-6-15(7-9-16)17-21-22-18-19(20-11-12-23(17)18)27-13-10-14-4-2-1-3-5-14/h1-9,11-12H,10,13H2	| QMCCJGVEGJOFQH-UHFFFAOYSA-N
MMV1634439	| COC(C=C1)=CC=C1C2=NN=C3C(SCCC4=CC=CC=C4)=NC=CN32 | 	InChI=1S/C20H18N4OS/c1-25-17-9-7-16(8-10-17)18-22-23-19-20(21-12-13-24(18)19)26-14-11-15-5-3-2-4-6-15/h2-10,12-13H,11,14H2,1H3	| GEUZYLOQEWPPTC-UHFFFAOYSA-N
MMV1634440	| C1(SCCC2=CC=CC=C2)=NC=CN3C1=NN=C3C4=CC=CC=C4 | 	InChI=1S/C19H16N4S/c1-3-7-15(8-4-1)11-14-24-19-18-22-21-17(23(18)13-12-20-19)16-9-5-2-6-10-16/h1-10,12-13H,11,14H2	| PXOUQPVRLQGOLD-UHFFFAOYSA-N
MMV1634441	| O=[[N+]](C(C=C1)=CC=C1C2=NN=C3C(SCCC4=CC=CC=C4)=NC=CN32)(C(C=C1)=CC=C1C2=NN=C3C(SCCC4=CC=CC=C4)=NC=CN32)[O-] | 	InChI=1S/C19H15N5O2S/c25-24(26)16-8-6-15(7-9-16)17-21-22-18-19(20-11-12-23(17)18)27-13-10-14-4-2-1-3-5-14/h1-9,11-12H,10,13H2	| NHMKPHMAQGUBEJ-UHFFFAOYSA-N
MMV1634442	| C1(NCCC2=CC=CC=C2)=NC=CN3C1=NN=C3C4=CC=CC=C4	| InChI=1S/C19H17N5/c1-3-7-15(8-4-1)11-12-20-17-19-23-22-18(24(19)14-13-21-17)16-9-5-2-6-10-16/h1-10,13-14H,11-12H2,(H,20,21)	| UVSSRDWLOVROPH-UHFFFAOYSA-N
MMV1634443	| COC(C=C1)=CC=C1C2=NN=C3C(NCCC4=CC=CC=C4)=NC=CN32 | 	InChI=1S/C20H19N5O/c1-26-17-9-7-16(8-10-17)19-23-24-20-18(22-13-14-25(19)20)21-12-11-15-5-3-2-4-6-15/h2-10,13-14H,11-12H2,1H3,(H,21,22)	| ZZFSYDDMUBYAFS-UHFFFAOYSA-N
MMV1634444	| O=[[N+]](C(C=C1)=CC=C1C2=NN=C3C(NCCC4=CC=CC=C4)=NC=CN32)(C(C=C1)=CC=C1C2=NN=C3C(NCCC4=CC=CC=C4)=NC=CN32)[O-] | 	InChI=1S/C19H16N6O2/c26-25(27)16-8-6-15(7-9-16)18-22-23-19-17(21-12-13-24(18)19)20-11-10-14-4-2-1-3-5-14/h1-9,12-13H,10-11H2,(H,20,21)	| HFBSNRIFQOQABE-UHFFFAOYSA-N
MMV1581298	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)(O)C4=CC=C(F)C(F)=C4)N32 | 	InChI=1S/C21H16F4N4O4/c22-15-6-3-13(7-16(15)23)21(31,10-30)11-32-18-9-26-8-17-27-28-19(29(17)18)12-1-4-14(5-2-12)33-20(24)25/h1-9,20,30-31H,10-11H2	| GXKONCOXFIUYEL-UHFFFAOYSA-N
MMV1581295	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)(O)C4=CC=CC=C4)N32 | 	InChI=1S/C21H18F2N4O4/c22-20(23)31-16-8-6-14(7-9-16)19-26-25-17-10-24-11-18(27(17)19)30-13-21(29,12-28)15-4-2-1-3-5-15/h1-11,20,28-29H,12-13H2	| LVBNVRWXODMMAV-UHFFFAOYSA-N
MMV689970	| C12=NN=C(C3=CC=CC=C3)N1C(OCCC4=CC=CC=C4)=CN=C2	| InChI=1S/C19H16N4O/c1-3-7-15(8-4-1)11-12-24-18-14-20-13-17-21-22-19(23(17)18)16-9-5-2-6-10-16/h1-10,13-14H,11-12H2	| YRTHPBSIEMFKFB-UHFFFAOYSA-N
MMV1634445	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(COC4=CN=CC5=NN=C(C6=CC=C(OC(F)F)C=C6)N54)(CO)C7=CC=CC=C7)N32	| InChI=1S/C34H26F4N8O5/c35-32(36)50-24-10-6-21(7-11-24)30-43-41-26-14-39-16-28(45(26)30)48-19-34(18-47,23-4-2-1-3-5-23)20-49-29-17-40-15-27-42-44-31(46(27)29)22-8-12-25(13-9-22)51-33(37)38/h1-17,32-33,47H,18-20H2	| SBKLVTZSIUTYAA-UHFFFAOYSA-N
MMV1634446	| NC1=C2C(C(C3=CC=CC(S(=O)(N)=O)=C3)=CN2)=NC=N1	| InChI=1S/C12H11N5O2S/c13-12-11-10(16-6-17-12)9(5-15-11)7-2-1-3-8(4-7)20(14,18)19/h1-6,15H,(H2,13,16,17)(H2,14,18,19)	| AZDIWLYPDODQNA-UHFFFAOYSA-N
MMV1634447	| FC(C=C1)=CC=C1CN(CC2)CCN2C3=C4C(C=C(C5=CC=CC(S(N)(=O)=O)=C5)S4)=NC=N3 | InChI=1S/C23H22FN5O2S2/c24-18-6-4-16(5-7-18)14-28-8-10-29(11-9-28)23-22-20(26-15-27-23)13-21(32-22)17-2-1-3-19(12-17)33(25,30)31/h1-7,12-13,15H,8-11,14H2,(H2,25,30,31) | 	OWXZZWFFXSEZNL-UHFFFAOYSA-N
MMV1634448	| NS(C1=CC=CC(C2=CC3=NC=NC(N(C)C)=C3S2)=C1)(=O)=O | 	InChI=1S/C14H14N4O2S2/c1-18(2)14-13-11(16-8-17-14)7-12(21-13)9-4-3-5-10(6-9)22(15,19)20/h3-8H,1-2H3,(H2,15,19,20)	| CGTVWFYTOADSRO-UHFFFAOYSA-N
MMV1634449	| NC1=C2C(C=C(C3=CC=CC(C(O)=O)=C3)S2)=NC=N1 | 	InChI=1S/C13H9N3O2S/c14-12-11-9(15-6-16-12)5-10(19-11)7-2-1-3-8(4-7)13(17)18/h1-6H,(H,17,18)(H2,14,15,16) | 	JYCLMKQWHKSRJT-UHFFFAOYSA-N
MMV897698	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32 | 	InChI=1S/C20H16F2N4O2/c21-20(22)28-16-8-6-15(7-9-16)19-25-24-17-12-23-13-18(26(17)19)27-11-10-14-4-2-1-3-5-14/h1-9,12-13,20H,10-11H2	| AVBCIJLYABLIRW-UHFFFAOYSA-N
MMV1634450	| O=C(CSC1=C2C(C=C(C3=CC=CC(OC)=C3)S2)=NC=N1)O | 	InChI=1S/C15H12N2O3S2/c1-20-10-4-2-3-9(5-10)12-6-11-14(22-12)15(17-8-16-11)21-7-13(18)19/h2-6,8H,7H2,1H3,(H,18,19)	| DYCCEQUNLMNCFJ-UHFFFAOYSA-N
MMV1634451	| CC(C(N=C1)=CC=C1C2=CC3=NC=NC(SCC(O)=O)=C3S2)=O | 	InChI=1S/C15H11N3O3S2/c1-8(19)10-3-2-9(5-16-10)12-4-11-14(23-12)15(18-7-17-11)22-6-13(20)21/h2-5,7H,6H2,1H3,(H,20,21)	| LGDNGRNEECNYDP-UHFFFAOYSA-N
MMV1634452	| O=C(CSC1=C2C(SC(C3=CC=CC(SC)=C3)=C2)=NC=N1)O | 	InChI=1S/C15H12N2O2S3/c1-20-10-4-2-3-9(5-10)12-6-11-14(21-7-13(18)19)16-8-17-15(11)22-12/h2-6,8H,7H2,1H3,(H,18,19)	| MNWOYBNZZSNGOO-UHFFFAOYSA-N
MMV1634453	| O=C(CSC1=C2C(C=C(C3=CC=CC(OC(F)(F)F)=C3)S2)=NC=N1)O | 	InChI=1S/C15H9F3N2O3S2/c16-15(17,18)23-9-3-1-2-8(4-9)11-5-10-13(25-11)14(20-7-19-10)24-6-12(21)22/h1-5,7H,6H2,(H,21,22)	| LVPPRPZWXKYNRR-UHFFFAOYSA-N
MMV1634454	| O=C(C)NC1=CC(C2=CC3=NC=NC(SCC(O)=O)=C3S2)=CC=C1	| InChI=1S/C16H13N3O3S2/c1-9(20)19-11-4-2-3-10(5-11)13-6-12-15(24-13)16(18-8-17-12)23-7-14(21)22/h2-6,8H,7H2,1H3,(H,19,20)(H,21,22)	| QITKDVLQZKEZLA-UHFFFAOYSA-N
MMV1634455	| O=C(CSC1=C2C(C=C(C3=CC=CS3)S2)=NC=N1)O	| InChI=1S/C12H8N2O2S3/c15-10(16)5-18-12-11-7(13-6-14-12)4-9(19-11)8-2-1-3-17-8/h1-4,6H,5H2,(H,15,16)	| AWGWMRKFZPUBMU-UHFFFAOYSA-N
MMV1634456	| O=C(CSC1=C2C(C=C(C3=CC=CC(N4CCOCC4)=C3)S2)=NC=N1)O | 	InChI=1S/C18H17N3O3S2/c22-16(23)10-25-18-17-14(19-11-20-18)9-15(26-17)12-2-1-3-13(8-12)21-4-6-24-7-5-21/h1-3,8-9,11H,4-7,10H2,(H,22,23)	| YNGXIFAWCXNJLT-UHFFFAOYSA-N
MMV1634457	| CS(C1=CC(C2=CC3=NC=NC(SCC(O)=O)=C3S2)=CC=C1)(=O)=O	 | InChI=1S/C15H12N2O4S3/c1-24(20,21)10-4-2-3-9(5-10)12-6-11-14(23-12)15(17-8-16-11)22-7-13(18)19/h2-6,8H,7H2,1H3,(H,18,19)	| BTGDYEPQMXMGFI-UHFFFAOYSA-N

**Comment by mattodd** [comment]
Great work from everyone @mbhebhe @maratsydney @david1597 

Tha, it looks like there's an issue with a few of those SMILES above. Any obvious reason?

Let's keep this issue open until we obtain the data. When that happens, post the data to ELN and link to it from here, post a graphical summary on this page below, and then link from here to the wiki, to the page "data not yet included in the wiki" so that we know the data need to be folded in.

Super exciting to have all these compounds sent in. Amongst many other things, it's essential we see how the OHOH compounds do. If potent, they have the potential to become series frontrunners and we'd need to have them examined for solubility and clearance.

**Comment by mbhebhe** [comment]
@mattodd with those few SMILES, they have these symbols next to each other "[]()". These symbols are for linking. So GH read it as linking. The InChl and InChl are fine and can be used instead

**Comment by mattodd** [comment]
OK, nice one @mbhebhe. I wonder if [quoting text](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-text) works better, so that the blue hyperlink doesn't appear? @cdsouthan is there a way of testing whether these SMILES are being picked up correctly despite the inclusion of that hyperlink? Either way, the solution to this little nugget needs to be installed on the [TechOps wiki](https://github.com/OpenSourceMalaria/TechOps/wiki) before we close this issue. @mbhebhe can you please be sure to take care of that?

**Comment by edwintse** [comment]
I've found a fix. You need to add a backslash between [] and (). This removes the hyperlink and gives the correct smiles.

For example, **[C@H] (O)** (space added between) will be converted to this
MMV1634423	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(NC[C@H](O)C4=CC=CC=C4)N32
Adding \ between the brackets gives this instead
MMV1634423	| FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(NC[C@H]\(O)C4=CC=CC=C4)N32

This should make the correct SMILES searchable but can someone confirm? @mattodd I can add it to the TechOps wiki but I'll need edit access to it.

**Comment by cdsouthan** [comment]
For searching, you can check that SMILES string renders correctly in the PubChem structure search box https://pubchem.ncbi.nlm.nih.gov/search/search.cgi# . You will find the SMILES option under the "Identity/Similarity"  box.  Click on "Preview" and you see the image.   For newer structures, you may as well do the "Search" at the same time. 

My guess is you can do the same in Marvin,  ChemDraw, and even good ole' SciFinder

**Comment by MFernflower** [comment]
you can simply insert a ` at the start and end of each smiles string @mattodd 

`CCCC(=O)C1=C(C(=C(C=C1O)OC)CC2=C(C(C(=C(C2=O)C(=O)CCC)O)(C)C)O)O`

**Comment by edwintse** [comment]
But that doesn't work with a string that contains [] followed by ()

**Comment by MFernflower** [comment]
@edwintse the symbol used is the grave not an apostrophe

**Comment by edwintse** [comment]
Ah, right you are

**Comment by mattodd** [comment]
@cdsouthan my concern was with what a search engine *actually* sees. If it sees the text that we see on the page, then the rendering tricks above will work. If it actually sees the underlying structure of the web page (think the binary representation of the Matrix, vs. the Woman in the Red Dress, if you will) then is there a danger that the string will be perceived with hyperlinks, graves, double brackets? And therefore be perceived wrongly? The answer to this question may be simplest to derive through experimental test. Unless the answer is obvious.

**Comment by drc007** [comment]
Why not just enclose the SMILES in a <pre> tag as shown below? https://www.w3schools.com/tags/tag_pre.asp

<pre>
FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(NC[C@H](O)C4=CC=CC=C4)N32
</pre>

**Comment by drc007** [comment]
<img width="684" alt="screenshot 2018-11-22 at 06 55 26" src="https://user-images.githubusercontent.com/7080516/48886356-9a9c4a00-ee23-11e8-855c-9090852c6697.png">

**Comment by MFernflower** [comment]
@mattodd @mbhebhe When you get the chance can you push the results to this GHI????

**Comment by mbhebhe** [comment]
@MFernflower we have the potency results for SGS compounds. I created a new issue for the results #65. I will close this one once we have the potency results for the USyd compounds

**Comment by MFernflower** [comment]
#65 results are in!!
