### ISSUE TITLE
CO-ADD assay

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMalaria/Series4#64]
A selection of series 4 ( + the s3 singleton @mbhebhe ) molecules were sent to CO-ADD for testing of possible antibacterial and anti-yeast activity as per https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/577

### Results are in (April 3rd 2019)

Unfortunately all tested compounds didn't show inhibition higher than ~30%. All compounds have been tested at a fixed concentration of 32 ug/mL. Here is excel spreadsheet with results. [CO-ADD_data_15Mar2019.xlsx](https://github.com/OpenSourceMalaria/Series4/files/3038511/CO-ADD_data_15Mar2019.xlsx)

![co-aad compounds](https://user-images.githubusercontent.com/29498087/49258191-aec9f200-f488-11e8-967c-2be7df1333d2.png)

--------------------------------------------------------------------------------------------------						
--------------------------------------------------------------------------------------------------						
Internal ID 	|	SMILES	|	InChI	|	CnChI Key
--	|	--	|	--	|	--
MK113-1a	|	C12=NN=C(C3=CC=CC=C3)N1C(OCCC4=CC=CC=C4)=CN=C2	|	"InChI=1S/C19H16N4O/c1-3-7-15(8-4-1)11-12-24-18-14-20-13-17-21-22-19(23(17)18)16-9-5-2-6-10-16/h1-10,13-14H,11-12H2"	|	YRTHPBSIEMFKFB-UHFFFAOYSA-N
MK126-1b	|	COC(C=C1)=CC=C1C2=NN=C3C(OCCC4=CC=CC=C4)=NC=CN32	|	"InChI=1S/C20H18N4O2/c1-25-17-9-7-16(8-10-17)18-22-23-19-20(21-12-13-24(18)19)26-14-11-15-5-3-2-4-6-15/h2-10,12-13H,11,14H2,1H3"	|	KNDAUWHMGBUKCB-UHFFFAOYSA-N
MK114-1a	|	COC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4=CC=CC=C4)N32	|	"InChI=1S/C20H18N4O2/c1-25-17-9-7-16(8-10-17)20-23-22-18-13-21-14-19(24(18)20)26-12-11-15-5-3-2-4-6-15/h2-10,13-14H,11-12H2,1H3"	|	FOEYJDQRLPZFOG-UHFFFAOYSA-N
MK121-1b	|	COC(C=C1)=CC=C1C2=NN=C3C(SCCC4=CC=CC=C4)=NC=CN32	|	"InChI=1S/C20H18N4OS/c1-25-17-9-7-16(8-10-17)18-22-23-19-20(21-12-13-24(18)19)26-14-11-15-5-3-2-4-6-15/h2-10,12-13H,11,14H2,1H3"	|	GEUZYLOQEWPPTC-UHFFFAOYSA-N
MK127-1a	|	COC(C=C1)=CC=C1C2=NN=C3C=NC=C(SCCC4=CC=CC=C4)N32	|	"InChI=1S/C20H18N4OS/c1-25-17-9-7-16(8-10-17)20-23-22-18-13-21-14-19(24(18)20)26-12-11-15-5-3-2-4-6-15/h2-10,13-14H,11-12H2,1H3"	|	XKLPATLXLSUHOI-UHFFFAOYSA-N
MK096-1	|	C12=NN=CN1C(OCCC3=CC=CC=C3)=CN=C2	|	"InChI=1S/C13H12N4O/c1-2-4-11(5-3-1)6-9-18-13-12-16-15-10-17(12)8-7-14-13/h1-5,7-8,10H,6,9H2"	|	OVMOYCYDOGFLPO-UHFFFAOYSA-N
MK086-1	|	C12=NN=CN1C(SCCC3=CC=CC=C3)=CN=C2	|	"InChI=1S/C13H12N4S/c1-2-4-11(5-3-1)6-7-18-13-9-14-8-12-16-15-10-17(12)13/h1-5,8-10H,6-7H2"	|	SFKFITTZRQEVSE-UHFFFAOYSA-N
MK105-2	|	C1(NCCC2=CC=CC=C2)=NC=CN3C1=NN=C3	|	"InChI=1S/C13H13N5/c1-2-4-11(5-3-1)6-7-14-12-13-17-16-10-18(13)9-8-15-12/h1-5,8-10H,6-7H2,(H,14,15)"	|	ZKSCHIOOMCSXEE-UHFFFAOYSA-N
MK006-3	|	C12=NN=CN1C(OCCC3=CC=CC=C3)=CN=C2	|	"InChI=1S/C13H12N4O/c1-2-4-11(5-3-1)6-7-18-13-9-14-8-12-16-15-10-17(12)13/h1-5,8-10H,6-7H2"	|	VFFDMAJXCFVHJC-UHFFFAOYSA-N
MK035-1	|	FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C5C(NC=C5)=C4)N32)=CC=C1F	|	"InChI=1S/C21H15F2N5O/c22-16-4-1-13(9-17(16)23)6-8-29-20-12-24-11-19-26-27-21(28(19)20)15-3-2-14-5-7-25-18(14)10-15/h1-5,7,9-12,25H,6,8H2"	|	VHFREJHLTSVZGA-UHFFFAOYSA-N
MK065-1	|	FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(Cl)C(N)=C4)N32)=CC=C1F	|	"InChI=1S/C19H14ClF2N5O/c20-13-3-2-12(8-16(13)23)19-26-25-17-9-24-10-18(27(17)19)28-6-5-11-1-4-14(21)15(22)7-11/h1-4,7-10H,5-6,23H2"	|	UUAZLIWHOSTWRP-UHFFFAOYSA-N
MK067-1	|	FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=CC(N)=C4)N32)=CC=C1F	|	"InChI=1S/C19H15F2N5O/c20-15-5-4-12(8-16(15)21)6-7-27-18-11-23-10-17-24-25-19(26(17)18)13-2-1-3-14(22)9-13/h1-5,8-11H,6-7,22H2"	|	CQZOPOXKTPBXOH-UHFFFAOYSA-N
MK041-1	|	FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(N)C=C4)N32)=CC=C1F	|	"InChI=1S/C19H15F2N5O/c20-15-6-1-12(9-16(15)21)7-8-27-18-11-23-10-17-24-25-19(26(17)18)13-2-4-14(22)5-3-13/h1-6,9-11H,7-8,22H2"	|	PGJZGRJIPPSPJV-UHFFFAOYSA-N
MK094-1	|	C1(SCCC2=CC=CC=C2)=NC=CN3C1=NN=C3	|	"InChI=1S/C13H12N4S/c1-2-4-11(5-3-1)6-9-18-13-12-16-15-10-17(12)8-7-14-13/h1-5,7-8,10H,6,9H2"	|	QGQSZEIXFAHGEY-UHFFFAOYSA-N
MK139-1	|	C1(OCCC2=CC=CC=C2)=NC=CN3C1=NN=C3C4=CC=CC=C4	|	"InChI=1S/C19H16N4O/c1-3-7-15(8-4-1)11-14-24-19-18-22-21-17(23(18)13-12-20-19)16-9-5-2-6-10-16/h1-10,12-13H,11,14H2"	|	BKUOBYRSGGKOSW-UHFFFAOYSA-N
MK091-2	|	FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC5=C(C=C4)N=CN5)N32)=CC=C1F	|	"InChI=1S/C20H14F2N6O/c21-14-3-1-12(7-15(14)22)5-6-29-19-10-23-9-18-26-27-20(28(18)19)13-2-4-16-17(8-13)25-11-24-16/h1-4,7-11H,5-6H2,(H,24,25)"	|	OKICKLNNAMYKHW-UHFFFAOYSA-N
MNB6-8	|	NC1=C2C(C=C(C3=CC(S(N)(=O)=O)=CC=C3)S2)=NC=N1	|	"InChI=1S/C12H10N4O2S2/c13-12-11-9(15-6-16-12)5-10(19-11)7-2-1-3-8(4-7)20(14,17)18/h1-6H,(H2,13,15,16)(H2,14,17,18)"	|	MQMXDJVOZKMSNT-UHFFFAOYSA-N

[Compounds.to.send.to.CO-AAD.zip](https://github.com/OpenSourceMalaria/Series4/files/2688226/Compounds.to.send.to.CO-AAD.zip)

**Comment by mattodd** [comment]
[Note added to wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Evaluations-vs-Other-Organisms). Feel free to expand. Data can be linked there when comes in.

**Comment by MFernflower** [comment]
Closing - new GHI will be opened when data is recived for discussion about said data - wiki entry has been updated @mattodd @maratsydney

**Comment by maratsydney** [comment]
Results have been added to the first post. Main outcome: none of them active, for details see excel spreadsheet attached to the first post.

**Comment by mattodd** [comment]
Sad but true. In some senses, of course, it's useful _not_ to have activity vs other things. In any event, @maratsydney, can you please update the wiki (https://github.com/OpenSourceMalaria/Series4/wiki/Evaluations-vs-Other-Organisms) and @mbhebhe can you please do the same with the Series 3 wiki (you may need to create a similar page). Once that's done, I think that this Issue can be closed again - there's nothing else here that would be orphaned?

**Comment by MFernflower** [comment]
I'll close and crossref the mycetoma thread

**Comment by MFernflower** [comment]
Data has been put on wiki @mattodd closing this issue @maratsydney

**Comment by MFernflower** [comment]
@danaklug When you get a chance can you integrate this data into paper?

**Comment by danaklug** [comment]
@MFernflower Sure. I am wondering whether it would work best as a short paragraph in the text with the actual data in the supplemental info, since the compounds are inactive and it's sort of a sidebar to the main malaria story. Thoughts?

**Comment by MFernflower** [comment]
That's a good idea

**Comment by danaklug** [comment]
Will do. Will also work on getting a Google doc for the SI up and running.
