### ISSUE TITLE
Poster that was presented at RACI 2018 organic conference

### ISSUE THREAD

**Issue by maratsydney** [OpenSourceMalaria/Series4#66]
Here is a poster on OSM Series 4, that was presented at RACI 2018 organic conference in Perth. Please find pdf and PowerPoint versions below. Files also backed up at [ELN](https://au-mynotebook.labarchives.com/share/Marat%2520Korsik/NDU1LjB8MjkzNzAvMzUwL1RyZWVOb2RlLzI0MDU2MjM1Mjl8MTE1NS4w).
![1](https://user-images.githubusercontent.com/29498087/50191793-7cbef800-0383-11e9-84ab-bd4cc7f59f91.PNG)

[Marat Korsik RACI.Poster_2018_Perth_v3.0.pdf](https://github.com/OpenSourceMalaria/Series4/files/2692813/Marat.Korsik.RACI.Poster_2018_Perth_v3.0.pdf)
[Marat Korsik RACI.Poster_2018_Perth_v3.0.pptx](https://github.com/OpenSourceMalaria/Series4/files/2692814/Marat.Korsik.RACI.Poster_2018_Perth_v3.0.pptx)

**Comment by MFernflower** [comment]
The PPTX appears corrupted but the PDF is really high definition @maratsydney

**Comment by mattodd** [comment]
Link to Talks-Meetings-Publicity repo installed on S4 wiki, and the above poster files uploaded to that repo. Closing.
