### ISSUE TITLE
Master list

### ISSUE THREAD

**Issue by cdsouthan** [OpenSourceMalaria/Series4#68]
Where is the latest SAR master list, please @edwintse @mattodd ? Its time for the ~6 monthly PubChem bulk cross-check update but I need a list of InChIKeys.  Also, as mentioned before, if the sub-100 nM front runners can be highlighted I'll see if I can arrange for least these to have PubChem and BioAssay entries to go in the paper :)

**Comment by mattodd** [comment]
I assume you found? All the sources of data are linked on the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Sources-of-Data#molecules-and-how-to-visualize-them). I'll add a note to the [front page](https://github.com/OpenSourceMalaria/Series4).
(@edwintse - just checking: all the data for all the compounds are in the Master List, right? You double-checked when you brought the wiki up to date?)
@cdsouthan if OK can you please close this Issue?
