### ISSUE TITLE
Next batch of compounds sent for biological testing Oct 2017

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/Series4#8]
The second batch of compounds from this years work (shown below) have now been shipped to Dundee for screening against _P. falciparum_.

THE RELEVANT POTENCY DATA HAS BEEN RECEIVED AND IS POSTED [HERE](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/Nzg5LjF8MTUwOS82MDcvVHJlZU5vZGUvNDg3MjUwMjcwfDIwMDMuMQ==
).
--------------------------------------------------------------------------------------------------
- Top row: Carborane derivatives
- 2nd row: Hydroxy compound based on the lead result from Pfizer (#3), heterocyclic derivatives, cyclic acetal for comparison to acyclic acetal/ketone ([#517](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/517))
- 3rd row: Benzylic amines furthering the series ([#504](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/504))
- Last row: Compounds made through Suzuki coupling ([#537](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/537))

![dundee compounds 191017](https://user-images.githubusercontent.com/18062981/31699733-4d0ef02e-b410-11e7-9964-5ced8af7e621.jpeg)
--------------------------------------------------------------------------------------------------
MMV Number | SMILES | InChI | InChI Key
-- | -- | -- | --
MMV1576784 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC/C4=C/BBBBBBBBBB4)N32 | InChI=1S/C16H22B10F2N4O2/c27-16(28)34-12-3-1-10(2-4-12)15-31-30-13-8-29-9-14(32(13)15)33-6-5-11-7-17-19-21-23-25-26-24-22-20-18-11/h1-4,7-9,16-26H,5-6H2/b11-7- | AGPVLTOPROUGPQ-XFFZJAGNSA-N
MMV1576785 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(N4CCOCC4)C5=CC=CC=C5)N32 | InChI=1S/C24H23F2N5O3/c25-24(26)34-19-8-6-18(7-9-19)23-29-28-21-14-27-15-22(31(21)23)33-16-20(17-4-2-1-3-5-17)30-10-12-32-13-11-30/h1-9,14-15,20,24H,10-13,16H2 | NLNZVWQRJHUCOA-UHFFFAOYSA-N
MMV1576786 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCN4CC5(COC5)C4)N32 | InChI=1S/C19H19F2N5O3/c20-18(21)29-14-3-1-13(2-4-14)17-24-23-15-7-22-8-16(26(15)17)28-6-5-25-9-19(10-25)11-27-12-19/h1-4,7-8,18H,5-6,9-12H2 | CWOUGAWUCYKRFC-UHFFFAOYSA-N
MMV1576787 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4=CC=C(CO)C=C4)N32 | InChI=1S/C20H16F2N4O3/c21-20(22)29-16-7-5-15(6-8-16)19-25-24-17-9-23-10-18(26(17)19)28-12-14-3-1-13(11-27)2-4-14/h1-10,20,27H,11-12H2 | VIQWBWLDUDXSBJ-UHFFFAOYSA-N
MMV1576788 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCCC4COC4)N32 | InChI=1S/C17H16F2N4O3/c18-17(19)26-13-3-1-12(2-4-13)16-22-21-14-7-20-8-15(23(14)16)25-6-5-11-9-24-10-11/h1-4,7-8,11,17H,5-6,9-10H2 | VMXSRABLXQMXLK-UHFFFAOYSA-N
MMV1576789 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC4(OCCO4)C5=CC(F)=C(F)C=C5)N32 | InChI=1S/C22H16F4N4O4/c23-16-6-3-14(9-17(16)24)22(32-7-8-33-22)12-31-19-11-27-10-18-28-29-20(30(18)19)13-1-4-15(5-2-13)34-21(25)26/h1-6,9-11,21H,7-8,12H2 | UAZNIGDYRZOARG-UHFFFAOYSA-N
MMV1576790 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC/C4=C/BBBBB[BH]5[BH]([H]5)BB4)N32.[Cs+] | InChI=1S/C16H22B9F2N4O2.Cs/c26-16(27)33-12-3-1-10(2-4-12)15-30-29-13-8-28-9-14(31(13)15)32-6-5-11-7-17-19-20-21-23-25-24(34-25)22-18-11;/h1-4,7-9,16-25H,5-6H2;/q;+1/b11-7-; | GZUNPULXOLJYSG-AJULUCINSA-N
MMV1576791 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(N(CC)CC)C4=CC(F)=C(F)C=C4)N32 | InChI=1S/C24H23F4N5O2/c1-3-32(4-2)20(16-7-10-18(25)19(26)11-16)14-34-22-13-29-12-21-30-31-23(33(21)22)15-5-8-17(9-6-15)35-24(27)28/h5-13,20,24H,3-4,14H2,1-2H3 | FFKUJTSUMDVIQH-UHFFFAOYSA-N
MMV1576792 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(N(CC)C)C4=CC(F)=C(F)C=C4)N32 | InChI=1S/C23H21F4N5O2/c1-3-31(2)19(15-6-9-17(24)18(25)10-15)13-33-21-12-28-11-20-29-30-22(32(20)21)14-4-7-16(8-5-14)34-23(26)27/h4-12,19,23H,3,13H2,1-2H3 | XPBTWBXREHLVRP-UHFFFAOYSA-N
MMV1576793 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(C(N)=O)C=C4)N32)=CC=C1F | InChI=1S/C20H15F2N5O2/c21-15-6-1-12(9-16(15)22)7-8-29-18-11-24-10-17-25-26-20(27(17)18)14-4-2-13(3-5-14)19(23)28/h1-6,9-11H,7-8H2,(H2,23,28) | INLVQLIAJLYDGP-UHFFFAOYSA-N
MMV1576794 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC(C(N)=O)=CC=C4)N32)=CC=C1F | InChI=1S/C20H15F2N5O2/c21-15-5-4-12(8-16(15)22)6-7-29-18-11-24-10-17-25-26-20(27(17)18)14-3-1-2-13(9-14)19(23)28/h1-5,8-11H,6-7H2,(H2,23,28) | SUVZMBHYRLCWQO-UHFFFAOYSA-N
MMV1576795 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(C(N(C)C)=O)C=C4)N32)=CC=C1F | InChI=1S/C22H19F2N5O2/c1-28(2)22(30)16-6-4-15(5-7-16)21-27-26-19-12-25-13-20(29(19)21)31-10-9-14-3-8-17(23)18(24)11-14/h3-8,11-13H,9-10H2,1-2H3 | VILLYIKHHVUPAT-UHFFFAOYSA-N
MMV1576796 | BrC1=NN=C2C=NC=C(OCCC3=CC(F)=C(F)C=C3)N21 | InChI=1S/C13H9BrF2N4O/c14-13-19-18-11-6-17-7-12(20(11)13)21-4-3-8-1-2-9(15)10(16)5-8/h1-2,5-7H,3-4H2 | MNOZFILPXCZGRJ-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
Those carboranes look insane!

**Comment by edwintse** [comment]
I believe they were put into the assay end of last week/beginning of this week. Hopefully won't be too long.

**Comment by edwintse** [comment]
We have just received the 1st run potency data from Dundee (linked in the original post above).

**Comment by MFernflower** [comment]
Fantastic! Interesting how that one carborane was so potent - @edwintse Do you have any more of that carborane alcohol in stock? - I'd like to see it Willamson'ed to some bromobenzene and the resulting phenyl ether be shipped off for testing - I bet that carborane is acting as a membrane distributor - given the sub nanomolar potency

**Comment by edwintse** [comment]
UPDATE:
The 2nd run potency data has been received. The values in the image on the ELN have been updated. The original image has been moved to the bottom of the page. An export of the data from ScienceCloud has also been uploaded to that page. These values will now be added to the master list.

**Comment by edwintse** [comment]
UPDATE:
MMV1576784, MMV1576785, MMV1576789, MMV1576790, and MMV1576795 were tested for cytotoxicity  and were are all inactive at >10uM in HepG2.

**Comment by MFernflower** [comment]
@edwintse so it's safe to say that the boron compound was killing parasite
by atp4 blockcade as opposed to membrane rupture? We should try diffrent
groups on the dioxolane ring!

**Comment by MedChemProf** [comment]
@mattodd @david1597 @drc007 @cdsouthan Merry Christmas everyone. I had a thought over the past few days on a concern regarding some of the recent activity data. Some great work being done on the design and synthesis. My concern is that batches of these compounds are then being sent for testing without the appropriate standards being synthesized and sent along with them. I am sure the assays being run are using an antimalarial standard, probably a commercially available drug, but not an internal standard that has been run in previous assays and in different labs. For instance, we always include MMV639565 (OSM-S-272) that we synthesized ourselves. I have seen compounds synthesized (and purified) by different chemists giving misleading results for a variety of reasons, and an internal standard such as the one mentioned, would have prevented moving in a false direction. Our throughput is minimal and resources limited, so every result has to be vetted as best as possible. I apologize if this is already being done and I have misread the results. I just wanted to voice my concern that an agreed upon internal standard should be included in each assay if possible. Again, my opinion and I think you all are doing great work.

**Comment by mattodd** [comment]
Hi @MedChemProf - yes, every assay at Dundee includes a positive control compound (from Dundee) but we don't include a control from us, no. We could always do that, but in my view it's not crucial. I think we should wait and compare analytical data on the Pfizer compound before we pass judgement on that situation. If we both think we're testing the same compound based on the analytical data then something else might be going on.
